### ISSUE TITLE
Probably wrong colour for popup messages.

### ISSUE THREAD

**Issue by Nachtalb** [mallowigi/material-theme-jetbrains-eap#101]
Probably wrong colour for popup messages.

![image](https://user-images.githubusercontent.com/9467802/28705618-ecce23a4-7370-11e7-98d0-41bcdbbbecbf.png)
![image](https://user-images.githubusercontent.com/9467802/28705996-83e86d3e-7372-11e7-902f-accc0ce2d94d.png)

### Summary

The popup messages should probably not have the Darcula theme background colour 

### Environment

```
PyCharm 2017.2
Build #PY-172.3317.103, built on July 25, 2017
Licensed to Nick Espig
Subscription is active until October 15, 2017
For educational use only.
JRE: 1.8.0_152-release-915-b5 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6
```
* Material Theme EAP 0.7.0.3

* OS X 10.12.6
* Windows ?
* Linux ?

**Comment by mallowigi** [comment]
Nope, this is purely intentional to have the style as material design popups (see examples in google apps)
