### ISSUE TITLE
Probably wrong colour for highlighted commits in version control.

### ISSUE THREAD

**Issue by Nachtalb** [mallowigi/material-theme-jetbrains-eap#102]
Probably wrong colour for highlighted commits in version control.

![image](https://user-images.githubusercontent.com/9467802/28705710-60050d6a-7371-11e7-936e-3cb36efb117e.png)

In the white theme too: 
![image](https://user-images.githubusercontent.com/9467802/28705970-68ca90d6-7372-11e7-8f50-f45699aa782f.png)

### Steps to reproduce 
1. Open "Version Control"
2. Click on the little gear icon
3. Activate "Current Branch" in dropdown

### Environment

```
PyCharm 2017.2
Build #PY-172.3317.103, built on July 25, 2017
Licensed to Nick Espig
Subscription is active until October 15, 2017
For educational use only.
JRE: 1.8.0_152-release-915-b5 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6
```
* Material Theme EAP 0.7.0.3

* OS X 10.12.6
* Windows ?
* Linux ?

**Comment by mallowigi** [comment]
I'm not sure that this panel is customizable, but I will try to look at it and see if there is something that can be done.

**Comment by mallowigi** [comment]
Should be better now
