### ISSUE TITLE
Bad readable activated bar tabs and switcher

### ISSUE THREAD

**Issue by Nachtalb** [mallowigi/material-theme-jetbrains-eap#103]
In the white theme the tabs in the bars like "Version Control" and so on, do not really have a good readable color when activated and in the switcher when hovered:

![image](https://user-images.githubusercontent.com/9467802/28706109-1edf312e-7373-11e7-8713-73adc01d5879.png)
![image](https://user-images.githubusercontent.com/9467802/28706111-216824f0-7373-11e7-994c-085640b7ca70.png)
### Environment

```
PyCharm 2017.2
Build #PY-172.3317.103, built on July 25, 2017
Licensed to Nick Espig
Subscription is active until October 15, 2017
For educational use only.
JRE: 1.8.0_152-release-915-b5 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6
```
* Material Theme EAP 0.7.0.3

* OS X 10.12.6
* Windows ?
* Linux ?

**Comment by mallowigi** [comment]
should be better now
