### ISSUE TITLE
listening debug icon is turned

### ISSUE THREAD

**Issue by saintho** [mallowigi/material-theme-jetbrains-eap#109]
listening debug icon is turned, When the listening debug is opened, the icon display is closed, When the listening debug is close, the icon display is open,

**Comment by mallowigi** [comment]
![image](https://user-images.githubusercontent.com/5015756/28826780-f577251c-76d3-11e7-9c63-751ef2c868c6.png)

![image](https://user-images.githubusercontent.com/5015756/28826787-fc659b2e-76d3-11e7-9e2d-76df7e44d060.png)

Dont know what you mean

**Comment by mallowigi** [comment]
Actually I know what you mean and I changed the behavior because what we are displaying are buttons to "listen to debug" (hence the green phone) or "stop listening" (hence the red phone). The original buttons are wrong in my opinion.
