### ISSUE TITLE
[UX] Cannot see or distinguish project tree items

### ISSUE THREAD

**Issue by vemilyus** [mallowigi/material-theme-jetbrains-eap#110]
As the title says, it's very hard to distinguish items in the tree view of the "Project" tool, because all items except the selected one have one color: Gray!

If you now factor in various overlays like the one that denotes files/dirs that are marked as excluded, you can't see anything.

Also, I use the ".ignore" plugin by hsz and only expect ignored files to be grayed out.

![confusingux](https://user-images.githubusercontent.com/7115009/28832882-f8b9e642-76dd-11e7-9fff-cc7c64097801.png)

Plugin Version: 0.7.3.1

IntelliJ IDEA 2017.2.1
Build #IU-172.3544.18, built on July 25, 2017
Licensed to ***
Subscription is active until ***
JRE: 1.8.0_152-release-915-b6 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

**Comment by mallowigi** [comment]
Oh for the love of god...

![image](https://user-images.githubusercontent.com/5015756/28831630-c61bbd96-76e2-11e7-9687-3dd211f7904a.png)

This is the sublime plugin.

**Comment by mallowigi** [comment]
Also, you are probably using File Colors from another Theme (Default), so if you change it to Darker it would be better already.

**Comment by vemilyus** [comment]
I'm using the File Colors of the darker theme, which is also the active UI theme. 

And this dark gray text is something I already don't like in the sublime plugin. Do we really have to do it that way for IntelliJ or can we make some improvements for the sake of usability?

**Comment by mallowigi** [comment]
I really want it to be like the plugin but it looks like a lot of people are being confused by it.

I will decide in the next few weeks whether to allow to change it or not, by leaving this behavior as default.

As for the File Colors that is not true, Darker File colors should be gray, not blue gray.

**Comment by vemilyus** [comment]
I have replaced the screenshot, just to prove that I am indeed using the darker File Colors.

**Comment by justinrusso** [comment]
+1 for this. I've grown to know a gray-ed out file is meant to be a file excluded from github, and white being the default. Now, if anything, the grayed color from ignoring is lighter than the themes color. If you want to stick with the sublime version, maybe make that default, and allow customizing the color, or at least just a "default" or white toggle of some sort.

Thanks for the awesome work! :)

![image](https://user-images.githubusercontent.com/25138621/28914223-ec919988-7808-11e7-956d-8c4e5a73045b.png)

**Comment by mallowigi** [comment]
I'm working on customizing the file colors, so it will be available in a future update
