### ISSUE TITLE
[FILE COLORS, DARKER, JAVA] Unreadable fields due to dark color

### ISSUE THREAD

**Issue by vemilyus** [mallowigi/material-theme-jetbrains-eap#111]
Since the 7.0.0 update the color of the fields of a Java-Class (static and non-static) has become a dark purple which is unreadable against the dark background of the darker File Colors.

![privatefields](https://user-images.githubusercontent.com/7115009/28869865-7a592136-777e-11e7-8aac-1c376de45835.PNG)

IntelliJ IDEA 2017.2.1
Build #IU-172.3544.18, built on July 25, 2017
Licensed to ***
Subscription is active until ***
JRE: 1.8.0_152-release-915-b6 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

**Comment by mallowigi** [comment]
Are you sure you don't have a modified version of Darker?

![image](https://user-images.githubusercontent.com/5015756/28871196-373c7200-778c-11e7-9b67-95c91fd4ec4f.png)

**Comment by vemilyus** [comment]
I deleted the icls files and voila, all fixed now. All I did before was hit 'Restore defaults...'

I derped out on this one.

**Comment by mallowigi** [comment]
So the restore defaults doesn't work? You should open an issue on Youtrack...
