### ISSUE TITLE
Weird checkboxes in settings

### ISSUE THREAD

**Issue by Nachtalb** [mallowigi/material-theme-jetbrains-eap#113]
I actually do not know if I did something wrong or if this is an bug. The checkboxes have a pretty weird colouring:  

![image](https://user-images.githubusercontent.com/9467802/28920789-a07287d8-7853-11e7-8632-54d92debcfb4.png)

```
PyCharm 2017.2
Build #PY-172.3317.103, built on July 25, 2017
Licensed to Nick Espig
Subscription is active until October 15, 2017
For educational use only.
JRE: 1.8.0_152-release-915-b5 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6
```

**Comment by Nachtalb** [comment]
After activating `Material Theme Components` it is working normally:

![image](https://user-images.githubusercontent.com/9467802/28921020-94e01966-7854-11e7-82e5-0eda000076e0.png)

**Comment by mallowigi** [comment]
I see. Thanks I forgot to fix the issue with Material Components disabled.

**Comment by mallowigi** [comment]
should be working now
