### ISSUE TITLE
What happens with Settings tree.....

### ISSUE THREAD

**Issue by xinkunZ** [mallowigi/material-theme-jetbrains-eap#116]
![image](https://user-images.githubusercontent.com/7759897/29102132-97ef7464-7ce9-11e7-9b51-a93a5b5893f8.png)

**Comment by mangaojian** [comment]
![763979a9-a1c2-4e9b-b798-0295802f230b](https://user-images.githubusercontent.com/24569545/29107298-1948b134-7d0c-11e7-820b-11e82f1f0275.png)
js icon

**Comment by mallowigi** [comment]
You're probably under Windows Look And Feel. Change to Darcula.

**Comment by mallowigi** [comment]
Damn it Jetbrains what have you done ><

**Comment by xinkunZ** [comment]
I don't know o(╯□╰)o......
![image](https://user-images.githubusercontent.com/7759897/29110283-c0256162-7d18-11e7-9fa1-2117c782df5c.png)

**Comment by mallowigi** [comment]
oh i know... jeez what a moron i am

**Comment by xinkunZ** [comment]
But Darker or Lighter theme works well....
![image](https://user-images.githubusercontent.com/7759897/29110367-02fb1b9e-7d19-11e7-8b37-9f953cf61fb4.png)

**Comment by mallowigi** [comment]
yeah yeah i know its my fault. I was doing a bit of cleanup and this affected the tree. Fixing it right away

**Comment by xinkunZ** [comment]
![image](https://user-images.githubusercontent.com/7759897/29110619-cde5e046-7d19-11e7-8059-eacf36d46400.png)

**Comment by mallowigi** [comment]
try now

**Comment by xinkunZ** [comment]
uh....why Jetbrain review your plugin so quickly!! 
My plugin will be publicly available for one day after uploading to plugin repository....
