### ISSUE TITLE
bad process bar and pop  title bar theme 

### ISSUE THREAD

**Issue by boliza** [mallowigi/material-theme-jetbrains-eap#117]
OS Ubuntu 16.04 LTS
IDEA 2017.2.1
eap 0.8.0.4
![_078](https://user-images.githubusercontent.com/1076043/29112700-3e907b92-7d21-11e7-80ae-06d0f275d6c9.png)

I have enable all choice in Material Design Components

additional info:
at the begin this seen god , something gone wrong after I toggle sometimes the Material Design Components

**Comment by mallowigi** [comment]
Was it new or has it always been like that. I'm seeing that in Linux a lot of stuff is not themed. I don't have Linux at home so I need to find a way to test it and fix it.

**Comment by boliza** [comment]
I will try every dialog and pop menu

**Comment by mallowigi** [comment]
I found the issue. Will release a fix in a few mins.

**Comment by boliza** [comment]
Thanks for your job. Love this theme very much
