### ISSUE TITLE
wrong colour for Settigs ... Blade

### ISSUE THREAD

**Issue by alehtrem** [mallowigi/material-theme-jetbrains-eap#118]
OS Ubuntu 17.04
IDEA 2017.2.1
eap 0.8.0.4
wrong colour for Settigs -> Languages & Frameworks -> PHP -> Blade: Text tags/Directives
![screenshot from 2017-08-09 11-17-31](https://user-images.githubusercontent.com/30339292/29114647-395df9a0-7cf5-11e7-97f2-2abbcb3e57d5.png)

**Comment by boliza** [comment]
![image](https://user-images.githubusercontent.com/1076043/29119723-e5954e82-7d39-11e7-8255-bed285d38f11.png)

**Comment by alehtrem** [comment]
Example old plugin 0.8.0
OS Ubuntu 17.04
IDEA 2017.2.1
![screenshot from 2017-08-09 14-33-43](https://user-images.githubusercontent.com/30339292/29121812-71d2ad4c-7d10-11e7-9fa2-2d1e92adf007.png)

Thanks! Beautiful theme !!!

**Comment by mallowigi** [comment]
Thanks for the update. I know what's going on.

**Comment by mallowigi** [comment]
Fixed.
