### ISSUE TITLE
Theme settings not saving after exit

### ISSUE THREAD

**Issue by michael-farwell** [mallowigi/material-theme-jetbrains-eap#120]
I'm on Mac OSX and just updated this plugin to 0.8.0.4. For some reason, all of my theme settings have reset to default. I reapplied them, but when I restart Pycharm they are reset to default again. Is this a bug or am I missing something that I should be doing to keep the changes saved?

**Comment by mallowigi** [comment]
I know what it is. Sorry for the troubles

**Comment by mallowigi** [comment]
I just released a version in the middle of a refactor so it could have broken stuff. I'm reverting the changes right away. Sorry for the troubles.

**Comment by michael-farwell** [comment]
Thank you for the quick response!!! Beautiful theme by the way!!!

**Comment by mallowigi** [comment]
should be back to normal now

**Comment by gencer** [comment]
@mallowigi nope, still has this issue. And until I realized this is caused by a bug i manually set all settings 3 times...

**Comment by mallowigi** [comment]
Can you send me the list of plugins you use?

**Comment by gencer** [comment]
![image](https://user-images.githubusercontent.com/1711576/29250591-9ab700b0-804d-11e7-9759-9746efcb712f.png)

**Comment by arifcatalyst** [comment]
I have the same issue. Theme preferences doesn't stick after restart.
