### ISSUE TITLE
Set File Tab Height below 25 pixels

### ISSUE THREAD

**Issue by detwetter** [mallowigi/material-theme-jetbrains-eap#123]
### Summary
Feature request:  Add ability to resize open File Tabs Height to less then 25 pixels to be more inline
with the size of the Compact Project tree size.  
...

### Expected behavior
Currently we can only resize the Tabs down to 25 pixels which is larger then the sizing of the Project Explorer tree.  See screenshot to see how it looks with file tabs down the right side and project explorer on the left size.  It would look nicer if we could get them to be the same sizes (height wise).
...

You can also add Screenshots for a better understanding.

![phpstorm](https://user-images.githubusercontent.com/29411391/29213675-3db803aa-7e72-11e7-9f9f-7da94bff077c.jpg)

### Environment

PhpStorm 2017.2.1
Build #PS-172.3544.41, built on August 2, 2017
Subscription is active until April 1, 2018
JRE: 1.8.0_152-release-915-b6 x86
JVM: OpenJDK Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by mallowigi** [comment]
The reason I put such a height is that because it is the default height from Jetbrains. Theoretically they must have a reason for this. My guess is that they are putting decorations on the title such a the wavy red line in case of errors.

But I will try and see if 18 is still doable.

**Comment by detwetter** [comment]
Hey @mallowigi thanks for your consideration of this feature request.  I totally understand if it's not possible to go shorter then the standard 25 pixels.

Also, I LOVE your work on this Material Theme!!!!!

**Comment by detwetter** [comment]
@mallowigi 19px looks perfect!!  This is fantastic!!  Now PHPStorm looks balanced for my setup!!

Thanks again!!
