### ISSUE TITLE
Terminal Broken

### ISSUE THREAD

**Issue by jabacchetta** [mallowigi/material-theme-jetbrains-eap#126]
### Summary

Attempting to open multiple terminal tabs via the + icon of the terminal (create new terminal session) is not working.

### Expected behavior

A new terminal tab should open.

### Actual behavior

A popup error is presented with the following message: "Can't Open Local Terminal"

### Steps to reproduce

1. Open WebStorm
2. Open the terminal tool window
3. Attempt to open a multiple terminal tabs/sessions

### Environment

Material Theme UI EAP Version: 0.9.0

WebStorm 2017.2.1
Build #WS-172.3544.34, built on July 31, 2017
Licensed to Jason Bacchetta
Subscription is active until November 30, 2017
JRE: 1.8.0_152-release-915-b6 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6

**Comment by mallowigi** [comment]
Can you try with version 0.8.1 and tell me if it's happening?

**Comment by jabacchetta** [comment]
Yes, it was working fine in the previous version.

**Comment by hassanazimi** [comment]
"Can't open local terminal" Also when I hove click on anything under "Editor > Code Style" in preference tap, the iDE will stuck. Very laggy. I disabled it altogether.

**Comment by mallowigi** [comment]
Finally got access to my computer. 

I didn't remove the feature in the end, just replaced uppercase to "spaced uppercase" and set it to false by default. And fixed the issue with the settings not saved.

Please tell me if there are other issues.
