### ISSUE TITLE
Editor Tabs Broken

### ISSUE THREAD

**Issue by jabacchetta** [mallowigi/material-theme-jetbrains-eap#127]
### Summary

There appears to be multiple issues with the editor tabs.

### Expected behavior

1. When disabling the "uppercase bold tabs" option, it should remain disabled, even after restarting.

2. When enabling the "hide file extension in editor tabs" option, the file extension should be hidden at all times.

### Actual behavior

1. The "uppercase bold tabs" option is enabled by default after every restart, even if it was previously disabled.

2. When the "uppercase bold tabs" option is enabled, the file extensions are shown, even if the "hide file extension in editor tabs" option is enabled.

### Steps to reproduce (if needed)

1. Open WebStorm
2. Go to Appearance & Behavior > Material Theme
3. Disabled "uppercase bold tabs"
4. Go to Editor > General > Editor Tabs
5. Enable "hide file extension in editor tabs"
5. Restart WebStorm

### Environment

Material Theme UI EAP Version: 0.9.0

WebStorm 2017.2.1
Build #WS-172.3544.34, built on July 31, 2017
Licensed to Jason Bacchetta
Subscription is active until November 30, 2017
JRE: 1.8.0_152-release-915-b6 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6

**Comment by vemilyus** [comment]
See #125

**Comment by mallowigi** [comment]
For the second issue, I will release a fix as soon as I get home.

**Comment by mallowigi** [comment]
Finally got access to my computer. 

I didn't remove the feature in the end, just replaced uppercase to "spaced uppercase" and set it to false by default. And fixed the issue with the settings not saved.

Please tell me if there are other issues.
