### ISSUE TITLE
.ignored files indistinguishable while using Dark theme

### ISSUE THREAD

**Issue by Avarel** [mallowigi/material-theme-jetbrains-eap#128]
### Summary
Dark unlike other themes, files ignored using the .ignore plugin (`.gitignore`) looks the same as any other file.

#### Default Dracula theme:
![](http://i.imgur.com/707eUur.png)
#### Default Material theme:
![](http://i.imgur.com/qz0XVda.png)
#### Palenight Material theme:
![](http://i.imgur.com/ko815WH.png)
#### Light Material theme:
![](http://i.imgur.com/yktROwq.png)

#### Dark theme, contrast on:
![](http://i.imgur.com/hNCgepv.png)
#### Without contrast:
![](http://i.imgur.com/Bj4zYi3.png)

**Comment by vemilyus** [comment]
See #110

**Comment by mallowigi** [comment]
They have the same color yeah. You can set your file colors if you want to, theoretically it works.

**Comment by Avarel** [comment]
Setting the file colors does not work right now.
