### ISSUE TITLE
Can't open multiple terminal and "Project Structure"

### ISSUE THREAD

**Issue by zhoujiealex** [mallowigi/material-theme-jetbrains-eap#130]
### Summary

- "terminal" is broken
-  can't open "Project Structure".

If uninstall EAP or install original plugin "Material Theme UI", everything is fine.

### Steps to reproduce (if needed)
issue1: open one terminal, then try to add another, boom...

![image](https://user-images.githubusercontent.com/1182420/29265078-42ae930e-8112-11e7-816f-095c4b09bb54.png) ![image](https://user-images.githubusercontent.com/1182420/29265095-512fd3b6-8112-11e7-9bb9-fd5dd7cf6752.png)

issue2: try to open menu "File->Project Structure..", but nothing happens
![image](https://user-images.githubusercontent.com/1182420/29265146-6e7a90aa-8112-11e7-8a6c-f485ed32bec4.png)

### Environment
IntelliJ IDEA 2017.2.1
Build #IU-172.3544.35, built on July 31, 2017
JRE: 1.8.0_152-release-915-b6 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6

**Comment by MrBlaise** [comment]
Same here (Mac OS X 10.12.6) and Webstorm 2017.2.1

**Comment by bernalrs** [comment]
Same on linux, I can't open multiple terminals anymore.

**Comment by mallowigi** [comment]
Finally got access to my computer. 

I didn't remove the feature in the end, just replaced uppercase to "spaced uppercase" and set it to false by default. And fixed the issue with the settings not saved.

Please tell me if there are other issues.
