### ISSUE TITLE
Verified/loaded breakpoint smaller than it should be

### ISSUE THREAD

**Issue by CrazyPython** [mallowigi/material-theme-jetbrains-eap#131]
An unloaded breakpoint looks like this:
![](https://i.imgur.com/5OatzRQ.png)
Whereas a loaded one looks like this:
![](https://i.imgur.com/MpLRJ5q.png)

I found the origin of the problem:
 - db_verified_breakpoint@2x.png is 24x24, while db_set_breakpoint@2x.png is 36x36
 - db_verified_breakpoint.png is 12x12, while db_set_breakpoint.png is 16x16

I'd be happy to send a pull request if I received the source SVG files.

**Comment by mallowigi** [comment]
should be fixed now
