### ISSUE TITLE
"Please Don't" Add Uppercase bold tabs to look more like MDTabs

### ISSUE THREAD

**Issue by JonathanYates** [mallowigi/material-theme-jetbrains-eap#132]
Noooo. Uppercase bold tabs in an IDE is simply wrong!! Visual Studio tried the same uppercase nonsense and there was uproar!! It may be ok on tabs for a general tab name but for file names it truly does does suck and takes up more space along the tab bar. It also looks very much out of place against everything else. Maybe ok on simple tabs in a mobile app, but not Tabs in an Ide or editor.

Please revert to proper case and we can all sleep easily!

Thank you.

**Comment by wtksana** [comment]
Second

**Comment by zhoujiealex** [comment]
+1  useless

**Comment by EiraStudios** [comment]
+1 At least have it disabled as default.

**Comment by iwex** [comment]
+1

**Comment by pakro** [comment]
Please make it either switchable with an option or remove it... This is really bad.

**Comment by MrBlaise** [comment]
Second that! Very bad looking.

**Comment by sebastiaanluca** [comment]
Disabling this uppercase nonsense doesn't work. Back to default uppercase on restart of PHPStorm :(

**Comment by MrBlaise** [comment]
@sebastiaanluca There is an issue about that already #125 
Download an older version until a fix is delivered (0.8.1.1) everything is fine there

**Comment by iraklisg** [comment]
In my view, the basic problem with bold tabs is that, in case you have two files with the same filename open (e.g services/users/index.js and repositories/users/index.js) you can note easily distinguish them, since any information about their path is not visible on the tabs

**Comment by renestalder** [comment]
Only took me a minute after the update to come to Github for giving the same opinion. The tabs shown in the Material Design Guidelines show a quite different use case: As navigation, which apply the uppercase rule from the buttons.

The text in the PHPStorm tabs aren't "button" actions. They may reflect actual text, similar to browser tabs.

**Comment by hoichi** [comment]
I have the tabs hidden, but the problem @iraklisg mentions is also present in **Recent files** (and **Switcher**):
![image](https://user-images.githubusercontent.com/3592345/29353564-5154790c-8273-11e7-87e8-962ab60d7685.png)
As opposed to:
![image](https://user-images.githubusercontent.com/3592345/29353602-75cb3492-8273-11e7-8940-7cfa4cca0fbf.png)

That said, you can turn it on pretty fast via command palette (aka **Find Action**, Ctrl-Shift-A by default):
![image](https://user-images.githubusercontent.com/3592345/29353766-0050e97c-8274-11e7-976b-e8d8997ff7dc.png)
Dunno why there's two settings, but either works.

**PS.** A bit of personal philosophy: I don't think any designer should follow _everything_ Material UI guides recommend. JetBrains IDEs inevitably pack a ton of information on one screen, and you cannot reduce it all to a few bold snippets and a red action button. I guess almost any programmer will take clarity and readability over style any day.
Not that Material Theme is not stylish with non-uppercase tabs. It's beautiful, and I hope I'll never have to come back to the stock themes, so keep up the terrific work!

**Comment by Alexgmin** [comment]
Uppercase file names make even less sense when you consider that filenames can be PascalCase, and when you transform that to SCREAMINGCASE you lose information.

**Comment by mallowigi** [comment]
I'll remove the feature as soon as I go home.

**Comment by mallowigi** [comment]
Just for the discussion, I had the idea when I discovered the extension point that gives the ability to modify tab titles. So I thought that it would be cool to be able to have uppercase titles in tabs like in MD.

But I later realized that file names are not supposed to be uppercase. It would have worked with debugger tabs, or code style tabs, but not filenames.

I've added a fix to put them in Pascal Case but still, it looks bad. And even worse the setting couldn't be changed!

So yeah I'll probably revert the feature back but I want to find a use to the extension point because I have no idea what could it be used for.

**Comment by JonathanYates** [comment]
Any progress reverting this please?

**Comment by mallowigi** [comment]
Finally got access to my computer. 

I didn't remove the feature in the end, just replaced uppercase to "spaced uppercase" and set it to false by default. And fixed the issue with the settings not saved.

Please tell me if there are other issues.

**Comment by JonathanYates** [comment]
Great I now have the correct casing for my files :)

I really don't know what value Spaced Uppercase would provide though for filenames. It just doesn't make any sense.

**Comment by mallowigi** [comment]
I already got used to it :)
