### ISSUE TITLE
Performance degraded (RubyMine) 

### ISSUE THREAD

**Issue by Justin-Maxwell** [mallowigi/material-theme-jetbrains-eap#133]
NOTE:  I'm not yet 100% certain this is due to the Plugin, but everything points to this.

Yesterday I upgraded to Material Theme UI EAP 0.9.0 - I also upgraded a couple of other plugins.

Around that time (realised in retrospect) IDE performance in RubyMine across the board took a dive, everything felt sluggish. Debugging, setting breakpoints, waiting for inspections, etc, in particular became painful.  

Today I disabled a few plugins incl MT-UI and everything came back to normal.  Have re-enabled MT-UI a couple of times and everything starts crawling again.  I will do more rigorous testing as soon as I have a moment, but thought it worth logging this as. For now I'm running with the plugin disabled and I miss it!

I thought is was worth reporting, to see if others are having similar issues.

**Comment by jabacchetta** [comment]
Noticing the same thing in WebStorm.

**Comment by mklenk** [comment]
Same here (IDEA 2017.2.2)
Xorg (1.18.4) is constantly using ~50% CPU when the theme is enabled. When I disable the plugin it goes down to ~1%

**Comment by mallowigi** [comment]
Can your try with version 0.8.1 and tell me if it is happening?

**Comment by jabacchetta** [comment]
Yes, it was working fine in the previous version.

**Comment by mallowigi** [comment]
maybe it works better now.
