### ISSUE TITLE
Preferences can't be accessed

### ISSUE THREAD

**Issue by jabacchetta** [mallowigi/material-theme-jetbrains-eap#134]
### Summary

Attempting to access some options from preferences is impossible.

### Expected behavior

The preferences should load.

### Actual behavior

An eternal "Loading..." screen is presented.

### Steps to reproduce

Open WebStorm
Open Preferences > Editor > Code Style > JavaScript

### Environment

Material Theme UI EAP Version: 0.9.0

WebStorm 2017.2.1
Build #WS-172.3544.34, built on July 31, 2017
Licensed to Jason Bacchetta
Subscription is active until November 30, 2017
JRE: 1.8.0_152-release-915-b6 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6

**Comment by matical** [comment]
Tested on PhpStorm and PyCharm, 2017.2.1 as well. All of the "Code Style" panes are inaccessible. Disabling the plugin restores functionality.

**Comment by renestalder** [comment]
I can also verify this.

**Comment by mallowigi** [comment]
Finally got access to my computer. 

I didn't remove the feature in the end, just replaced uppercase to "spaced uppercase" and set it to false by default. And fixed the issue with the settings not saved.

Please tell me if there are other issues.
