### ISSUE TITLE
Database datasource dialog broken

### ISSUE THREAD

**Issue by adaroobi** [mallowigi/material-theme-jetbrains-eap#135]
I am not sure if this is relative to #134 . However any dialog doesn't open when trying to modify datasource or add a new one. Just nothing pops up.

OS: Linux (Ubuntu 14.04)
PHPStorm 17.2.1

**Comment by mallowigi** [comment]
Finally got access to my computer. 

I didn't remove the feature in the end, just replaced uppercase to "spaced uppercase" and set it to false by default. And fixed the issue with the settings not saved.

Please tell me if there are other issues.

**Comment by adaroobi** [comment]
Welcome back :)
Just checked it out, now it is fixed along with the others.
Thanks.
