### ISSUE TITLE
Dialog Title Height

### ISSUE THREAD

**Issue by dudong0726** [mallowigi/material-theme-jetbrains-eap#136]
![image111111](https://user-images.githubusercontent.com/1704803/29357529-77f91da6-82aa-11e7-9132-0a9c8e6a2ea1.png)

### Summary
can we setting the height of the dialog title？
...

### Expected behavior

...

### Environment
* Windows7
* IDEA + 2017.2.1
* Plugin 0.9

**Comment by mallowigi** [comment]
I'd probably rather not. But if requested I'll do it.

If I have more than ten votes I'll add it.

**Comment by mallowigi** [comment]
Closing this since I don't want to develop it.

PRs are welcome.
