### ISSUE TITLE
BROKEN VERSION DO NOT UPDATE

### ISSUE THREAD

**Issue by mallowigi** [mallowigi/material-theme-jetbrains-eap#137]
The last version (9.0) is very much broken. The changes I've included have affected very important parts of the IDE and the MDTabs feature is not useable.

I'm currently on vacation so I don't have a computer near me so there will probably be no fixes until the end of the month.

In the meantime, please uninstall the plugin and install the material-theme-plugin from the main repository, version 0.8.1.

Thanks

**Comment by Alexgmin** [comment]
¿What else is broken other than the uppercase tabs?

**Comment by Stefan-Z-Camilleri** [comment]
Thank you for the heads up, I will do as you say and look forward to the next release.

Enjoy your holiday.

**Comment by Justin-Maxwell** [comment]
Thanks!

The 'Material Theme UI' plugin from repo installed version 0.8.2 - is this okay?  Or do we need to manually download/install 0.8.1?

Ta.

Also, have a great vacation.

**Comment by Stefan-Z-Camilleri** [comment]
@Justin-Maxwell the `Material Theme UI` is ok... it reports a lower version than 0.8.1, yet it's fine.

**Comment by michalmielczynski** [comment]
Reverted to 8.1.1 - 9.x is pretty unusable, I'm afraid. Waiting for the fixes! :+1:

**Comment by mallowigi** [comment]
Finally got access to my computer. 

I didn't remove the feature in the end, just replaced uppercase to "spaced uppercase" and set it to false by default. And fixed the issue with the settings not saved.

Please tell me if there are other issues.

**Comment by detwetter** [comment]
Still not retaining settings on restart......

**Comment by Justin-Maxwell** [comment]
0.9.2 still seems to cripple performance.  
0.8.2 seems fine for me.
