### ISSUE TITLE
Can't open Terminal

### ISSUE THREAD

**Issue by nWidart** [mallowigi/material-theme-jetbrains-eap#138]
### Summary

I'm using the EAP version, at 0.9.0. Since this update, I can't open the terminal anymore. When trying to do so, I'm getting "Can't open local Terminal" error.

### Expected behavior

Open the terminal in phpstorm.

### Actual behavior

"Can't Open Terminal" error.

![image](https://user-images.githubusercontent.com/882397/29365009-b53f90a6-8295-11e7-8f37-b361bfb701e3.png)

### Environment

* Operating system and version:
  * [ ] Windows ...
  * [x] Mac OS ...
  * [ ] Linux ...
* Material Theme release:
  * 0.9.0

**Comment by jabacchetta** [comment]
#126

**Comment by Kurre** [comment]
Latest version is broken, please see: https://github.com/mallowigi/material-theme-jetbrains-eap/issues/137

**Comment by nWidart** [comment]
I see, thank you! I've activated the non eap version for now until it's resolved. 

Thanks!

**Comment by hassanazimi** [comment]
Same here
