### ISSUE TITLE
Have python modules have the module icon

### ISSUE THREAD

**Issue by ohlookemus** [mallowigi/material-theme-jetbrains-eap#139]
Any way to have python modules have the module icon?

**Comment by mallowigi** [comment]
what is the module icon?

**Comment by ohlookemus** [comment]
![screen shot 2017-08-18 at 9 46 32 am](https://user-images.githubusercontent.com/700730/29468693-2e3fca60-83fa-11e7-8ca3-be6aca55a299.png)

In PyCharm, the module icon turns into this,

![screen shot 2017-08-18 at 9 47 27 am](https://user-images.githubusercontent.com/700730/29468722-440a8ac4-83fa-11e7-95ba-f62af97abd94.png)

**Comment by mallowigi** [comment]
I tried to reproduce this but I don't know how to make a module in Python... There is nothing of the sort in the menu...

Maybe you can right click on the folder and uncheck the "sources root" ?

**Comment by ohlookemus** [comment]
To have a python module the folder just needs to have an __init__.py file

**Comment by mallowigi** [comment]
should be fixed in latest version
