### ISSUE TITLE
Tool Buttons toggle icon blurry on high-res screens

### ISSUE THREAD

**Issue by renestalder** [mallowigi/material-theme-jetbrains-eap#140]
### Summary

In one of the latest updates, the icon for toggling the tool buttons was overwritten. This icon appears to be fine on normal displays, but is blurry on high-res screens. See screenshot, bottom left.

<img width="319" alt="screen shot 2017-08-19 at 14 16 06" src="https://user-images.githubusercontent.com/105358/29486577-b7c0ea36-84e9-11e7-80cd-3d0efc737fcf.png">

### Expected behavior

The tool buttons toggle icon should by crisp on all screens.

### Actual behavior

The tool buttons toggle icon is blurry.

### Steps to reproduce (if needed)

1. Material Design Components option activated

You can also add Screenshots for a better understanding.

### Environment

That should be quite the same on all high-res screens. For me it's a MacBook 12" Retina on latest macOS version.

**Comment by mallowigi** [comment]
I know, I was also surprised by this, but this is not the plugins fault but Jetbrains. If you disable the Material Icons you will see that the original icon is also blurry.

**Comment by renestalder** [comment]
The original icon is crisp for me.
<img width="274" alt="screen shot 2017-08-19 at 16 53 22" src="https://user-images.githubusercontent.com/105358/29487772-0535c48e-84ff-11e7-8d5b-fd97b4844e97.png">

**Comment by mallowigi** [comment]
damn it you're right, and I now understand why! And here I thought it was Jetbrains' fault...

You can only see that other icons are also affected: hide tool window, autoscroll to source... I'm feeling silly that didn't found out why! :embarassed:

Will issue a hotfix shortly.

**Comment by renestalder** [comment]
No worry. This isn't major or urgent. :)

**Comment by mallowigi** [comment]
should be fixed now
