### ISSUE TITLE
"Terminal" height is too high, make it tiny 

### ISSUE THREAD

**Issue by zhoujiealex** [mallowigi/material-theme-jetbrains-eap#141]
Just a feature request.

I do remember the terminal tab is tiny  in some version.
Where does it go in recent versions? Is is possible to make it tiny. 

![2017-08-20_13-28-47](https://user-images.githubusercontent.com/1182420/29492377-4b07197e-85ac-11e7-8678-7332daac1d55.jpg)

**Comment by mallowigi** [comment]
This is what caused the multiple errors in version 0.9.0 I reverted to this size for the time being until I find a fix.

**Comment by mallowigi** [comment]
I think I won't be fixing this. I'm done hacking the IDE, we're almost at a stable version and I don't want a fiasco like 0.9.0.
