### ISSUE TITLE
Jar files could not see clearly in Project tree

### ISSUE THREAD

**Issue by xinkunZ** [mallowigi/material-theme-jetbrains-eap#142]
![image](https://user-images.githubusercontent.com/7759897/29513470-0f7ec414-8698-11e7-86bb-0768c0babaa1.png)

Maybe there need a setting to change file name color......
BTW.  It is default theme~

**Comment by mallowigi** [comment]
You can simply edit the file color for "non-project files" to a darker blue (or something else).

You can also customize file colors for classes in Color Schemes > Material File Colors
