### ISSUE TITLE
name of erroneous files is not readable with a dark theme

### ISSUE THREAD

**Issue by loolooyyyy** [mallowigi/material-theme-jetbrains-eap#146]
File name of files with errors in theme is not readable in project side panel.

File name should be in contrast to background color (if a dark theme is chosen, it must be white? yellow? something light). Currently it's red and doesn't look good on dark gray.

P.S: I'm 50% red/green color blind. IDE's color blind filter is also turned on, but it's still not readable to me. Sorry if it looks okay to others.

![bug](https://user-images.githubusercontent.com/3070413/29603937-2943c3cc-87fb-11e7-8428-d41e1bec2c6b.png)

**Comment by loolooyyyy** [comment]
I wish I could change the color of regular file names too, to white perhaps.

**Comment by mallowigi** [comment]
There is a section under Appearance > Color Scheme > Material File Colors. This is the first time I've seen this color though, maybe it's because of the colorblind filter.

**Comment by loolooyyyy** [comment]
You're right, it was color-blindness filter. I'll close this issue then. thanks.
