### ISSUE TITLE
Endless loading of Material Theme settings

### ISSUE THREAD

**Issue by dimyriy** [mallowigi/material-theme-jetbrains-eap#149]
### Summary

Opening Material Theme settings under Appearance cause endless panel loading
<img width="1134" alt="screenshot 2017-08-24 13 54 22" src="https://user-images.githubusercontent.com/1125646/29663531-3a6078b0-88d4-11e7-9267-024bb0c56def.png">

and following exception to be thrown:

> cannot create configurable component: (minimum <= value <= maximum) is false
> java.lang.IllegalArgumentException: (minimum <= value <= maximum) is false
> 	at javax.swing.SpinnerNumberModel.<init>(SpinnerNumberModel.java:125)
> 	at javax.swing.SpinnerNumberModel.<init>(SpinnerNumberModel.java:147)
> 	at com.chrisrm.idea.config.ui.MTForm.init(MTForm.java:115)
> 	at com.chrisrm.idea.config.MTConfigurableBase.lambda$initComponent$0(MTConfigurableBase.java:159)
> 	at com.intellij.util.ui.UIUtil$13.run(UIUtil.java:2810)
> 	at com.intellij.util.ui.UIUtil.invokeAndWaitIfNeeded(UIUtil.java:2781)
> 	at com.intellij.util.ui.UIUtil.invokeAndWaitIfNeeded(UIUtil.java:2807)
> 	at com.chrisrm.idea.config.MTConfigurableBase.initComponent(MTConfigurableBase.java:157)
> 	at com.chrisrm.idea.config.MTConfigurableBase.createComponent(MTConfigurableBase.java:98)
> 	at com.intellij.openapi.options.ex.ConfigurableWrapper.createComponent(ConfigurableWrapper.java:164)
> 	at com.intellij.openapi.options.ex.ConfigurableCardPanel.a(ConfigurableCardPanel.java:73)
> 	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:47)
> 	at com.intellij.openapi.options.ex.ConfigurableCardPanel.createConfigurableComponent(ConfigurableCardPanel.java:69)
> 	at com.intellij.openapi.options.ex.ConfigurableCardPanel.create(ConfigurableCardPanel.java:55)
> 	at com.intellij.openapi.options.newEditor.ConfigurableEditor$1.create(ConfigurableEditor.java:70)
> 	at com.intellij.openapi.options.newEditor.ConfigurableEditor$1.create(ConfigurableEditor.java:67)
> 	at com.intellij.ui.CardLayoutPanel.a(CardLayoutPanel.java:88)
> 	at com.intellij.ui.CardLayoutPanel.b(CardLayoutPanel.java:116)
> 	at com.intellij.ui.CardLayoutPanel.a(CardLayoutPanel.java:132)
> 	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:314)
> 	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:416)
> 	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
> 	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
> 	at java.awt.EventQueue.access$500(EventQueue.java:98)
> 	at java.awt.EventQueue$3.run(EventQueue.java:715)
> 	at java.awt.EventQueue$3.run(EventQueue.java:709)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
> 	at com.intellij.ide.IdeEventQueue.g(IdeEventQueue.java:821)
> 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
> 	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
> 	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
> 	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
> 	at java.awt.Dialog.show(Dialog.java:1084)
> 	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:736)
> 	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:458)
> 	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1686)
> 	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1635)
> 	at com.intellij.openapi.options.newEditor.SettingsDialog.a(SettingsDialog.java:83)
> 	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:86)
> 	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:151)
> 	at com.intellij.openapi.options.newEditor.SettingsDialog.show(SettingsDialog.java:83)
> 	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:97)
> 	at com.intellij.ide.actions.ShowSettingsAction.perform(ShowSettingsAction.java:63)
> 	at com.intellij.ide.MacOSApplicationProvider$Worker.a(MacOSApplicationProvider.java:118)
> 	at com.intellij.ide.MacOSApplicationProvider$Worker.a(MacOSApplicationProvider.java:212)
> 	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:86)
> 	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:72)
> 	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:416)
> 	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
> 	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
> 	at java.awt.EventQueue.access$500(EventQueue.java:98)
> 	at java.awt.EventQueue$3.run(EventQueue.java:715)
> 	at java.awt.EventQueue$3.run(EventQueue.java:709)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
> 	at com.intellij.ide.IdeEventQueue.g(IdeEventQueue.java:821)
> 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

### Expected behavior

Material Theme settings panel opens normally.

### Actual behavior

Exception is thrown.

You can also add Screenshots for a better understanding.

### Environment
IntelliJ IDEA 2017.2.3
Build #IU-172.3968.16, built on August 22, 2017
Licensed to Genesys / Dmitry Bogdanov
Subscription is active until January 24, 2018
JRE: 1.8.0_152-release-915-b11 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6

**Comment by mallowigi** [comment]
#112
