### ISSUE TITLE
Some data displayed with too toxic colours. 

### ISSUE THREAD

**Issue by sharikovvladislav** [mallowigi/material-theme-jetbrains-eap#151]
### Summary

I have Material Theme Default (Darker Theme).
Some colours in it are too toxic. I found two problems at least.

### Expected behavior

I expect less toxic colours. 

### Actual behaviour

1. Deprecated colour. Here is output: http://i.imgur.com/01J5tho.png.
2. Code coverage colours: Output: http://i.imgur.com/FCswB78.jpg. 

### Steps to reproduce (if needed)

0. Should I list it?

You can also add Screenshots for a better understanding.

### Environment

webstorm data: http://i.imgur.com/RB3sYxq.jpg
MacOS version: 10.12.6
Material Theme UI version 0.8.2

**Comment by mallowigi** [comment]
I agree with you (though toxic is not the correct word for that)

For code coverage colors we can use the same colors as in the diff colors, as for deprecated... we can't use gray (it's for unused variables) nor any of the colors used in the syntax. Do you have a suggestion?

**Comment by sharikovvladislav** [comment]
For example darcula theme handles deprecated symbols rather good: http://i.imgur.com/AHvgbr9.png

Well colours from diff are not bad. Actually its ok to use red and and green but not these ones :) Not so bright. It is even hard to read text with that styles...

**Comment by mallowigi** [comment]
Ummmmmmm I can't see the code coverage colors you're seeing...

Are you sure you are not using your own?

**Comment by sharikovvladislav** [comment]
@mallowigi hmmm... I just tried on my MacBook and colours are ok. Let me try on my work pc. I had that problem there... 

by the way what is correct word for this colours? :) too bright?

**Comment by mallowigi** [comment]
Yeah kind of :)  but you probably referred to toxic waste with its lime green color

**Comment by sharikovvladislav** [comment]
Actually, I was on some conference. And English speaking guy did something in special dashboard and said "oh no, this colour is too toxic, let me change". Thats why I thoughts its ok to say this. Sry.

Ok, I will check same problem 28.08 when I will be at work.

**Comment by mallowigi** [comment]
Theoretically it should work and I changed the deprecated color in the latest release. Contact me if there are additional issues.

**Comment by sharikovvladislav** [comment]
Oh, sry. I forget to check. I will do it today at the evening. I will write there.

**Comment by sharikovvladislav** [comment]
I can not get coverage working :) Something went wrong ... =)

I will update this issue when I will get them.

Well, I have one screenshot at the header message. 

Env:

WebStorm 2016.3
Build #WS-163.7743.25, built on November 10, 2016
Licensed to ООО «ПС РнД»

JRE: 1.8.0_92-b14 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation

Also:

OS: Windows 7 Enterprise
Plugin version: 0.2.2 (https://image.prntscr.com/image/TLcoYHi1R-m2GSeLY6QITg.png)

**Comment by mallowigi** [comment]
Wow you have one old version! Sorry man but I'm not developing updates for 2016.X versions of the ide :(

--
Elior

**Comment by sharikovvladislav** [comment]
Oh cool. I just downloaded new one (2017.x). I updated to 2017.2.2 on macOS. So I think everything will be ok in new version. 

Cool! Thank you ! You are doing our world better :)
