### ISSUE TITLE
Custom Tree Line Height

### ISSUE THREAD

**Issue by hernandev** [mallowigi/material-theme-jetbrains-eap#152]
### Summary
Just setting Compact SideBar: true/false is not enough, compact is too compact and disabling it is too sparse.
...

### Expected behavior
setting a custom line height on the tree, instead just like we're allowed to on the sidebar identing

**Comment by mallowigi** [comment]
This is a change I already made for version 0.9 but because of hard to reproduce issues I couldn't release the version for the time being.

**Comment by hernandev** [comment]
thank you @mallowigi do you know which previous versions does not include the new tree spacing? So I can just rollback for now

**Comment by mallowigi** [comment]
i think version 0.4.0

**Comment by hernandev** [comment]
thanks

**Comment by hernandev** [comment]
@mallowigi installed EAP instead, thanks man!
