### ISSUE TITLE
More contrast for terminal

### ISSUE THREAD

**Issue by TobiasTimm** [mallowigi/material-theme-jetbrains-eap#165]
### Summary
In IntelliJ Community Edition the `Atom One Dark Theme` needs a bit more contrast for the terminal.
...

### Expected behavior
A bite more contrast.
...

### Actual behavior
The terminal has the same colors like the rest of the ide.
...

### Steps to reproduce (if needed)

1. Select `Atom One Dark Theme`

`Atom One Dark` in IntelliJ Community Edition

![materialtheme_eap_terminal](https://user-images.githubusercontent.com/10043789/30003513-5c8cc352-90be-11e7-8cdd-39f6d745c0d1.png)

### Environment

IntelliJ IDEA 2017.2.3
Build #IC-172.3968.16, built on August 22, 2017
JRE: 1.8.0_152-release-915-b11 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

Plugin Version: 0.10.2.3

**Comment by mallowigi** [comment]
What color scheme are you using?

**Comment by TobiasTimm** [comment]
@mallowigi `Atom One Dark Theme`

**Comment by mallowigi** [comment]
I'm talking about the color scheme, because that is what is setting the terminal background color, and this plugin doesn't contain an Atom One Dark scheme

**Comment by TobiasTimm** [comment]
@mallowigi  ah sry `Material Theme - Darker`

**Comment by TobiasTimm** [comment]
Was an issue with some old tweaked colors in the `Material Theme - Darker`
