### ISSUE TITLE
Spacegray

### ISSUE THREAD

**Issue by bobsoppe** [mallowigi/material-theme-jetbrains-eap#167]
### Summary
Spacegray as custom theme
https://github.com/kkga/spacegray/
...

### Expected behavior

...

### Actual behavior

...

### Steps to reproduce (if needed)

...

**Comment by mallowigi** [comment]
I'm not adding new themes at the moment. I will supply a way for people to share their custom themes and add new themes for those who have the most votes.

**Comment by bobsoppe** [comment]
Good to hear, I'll just wait on that functionality!
