### ISSUE TITLE
wrong background task process bar title color

### ISSUE THREAD

**Issue by boliza** [mallowigi/material-theme-jetbrains-eap#169]
* OS (Linux Ubuntu 16.04 LTS)
* IDEA 2017.2.3
* Plugin version 0.10.3

when the process bar not in focus,it appear like this:
![image](https://user-images.githubusercontent.com/1076043/30203867-29c8a48a-94b6-11e7-8f4b-b3b003849010.png)

**Comment by mallowigi** [comment]
I know about this but this is an hardcoded color and cannot be changed (AFAIK)
