### ISSUE TITLE
IDE font is reset on (re)start

### ISSUE THREAD

**Issue by sebastiaanluca** [mallowigi/material-theme-jetbrains-eap#171]
### Summary

When restarting, the IDE font is reset to a smaller size. The editor font stays the same, no issue there. There seem to be a few previous issues similar to this one.

### Expected behavior

Font settings are saved on quit.

### Actual behavior

Font settings get reset.

### Steps to reproduce (if needed)

1. Fix font settings (was set to a smaller size after material theme update)
2. Save preferences
3. Quit IDE
4. Open PHPStorm

An example of the small font everywhere but in the editor. Also shows you the setting I have to __uncheck__ to have it working again, but this only works the first time. On the second try (same session) I have to do this a few times to get the font to update in the IDE.

![screen shot 2017-09-18 at 18 00 17](https://user-images.githubusercontent.com/711940/30551588-3b07c950-9c9b-11e7-9720-d14d756d6648.png)

### Environment

PhpStorm 2017.3 EAP
Build #PS-173.2290.12, built on September 13, 2017
PhpStorm EAP User
Expiration date: October 13, 2017
JRE: 1.8.0_152-release-915-b12 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6

**Comment by sebastiaanluca** [comment]
Update: it also (seemingly randomly) resets it during use, one element at a time 😃  One tab had the font set as it should be, the others suddenly had a smaller font size.

**Comment by mallowigi** [comment]
Did you get an error "Failed to save settings" anyhow? It could be related.

Try from the latest version of the EAP

**Comment by sebastiaanluca** [comment]
No error or alert. Upgraded all to the latest, but can't seem to change it anymore. The font editor setting doesn't interfere with the IDE font now, but no way to change IDE font unless I override it.

Verified it only happens when the Material Theme EAP plugin is installed. Is the new smaller font a default setting or is this a bug?

**Comment by mallowigi** [comment]
What??? I don't understand.

![image](https://user-images.githubusercontent.com/5015756/30557058-ba4dd276-9cb5-11e7-97ef-fbc8a4291d56.png)
![image](https://user-images.githubusercontent.com/5015756/30557065-bf228576-9cb5-11e7-969c-3dd964154704.png)

This is my setting and it works fine. What is your issue?

**Comment by sebastiaanluca** [comment]
I'm not talking about the editor font, this is about the IDE (dialog, interface, sidebar, tab, …) font that suddenly changed with the second to last update.

Notice the difference in font family and size below (ignore colors and spacing).

### Original

![screen shot 2017-09-18 at 20 16 08](https://user-images.githubusercontent.com/711940/30557347-414d37b0-9cae-11e7-9c86-8f8f39358c2c.png)
![screen shot 2017-09-18 at 20 16 14](https://user-images.githubusercontent.com/711940/30557350-42beed82-9cae-11e7-804e-eb5d7ddec131.png)

### Material theme

![screen shot 2017-09-18 at 20 14 36](https://user-images.githubusercontent.com/711940/30557368-4a1ba2e6-9cae-11e7-9d5e-179619bcbfa8.png)
![screen shot 2017-09-18 at 20 14 42](https://user-images.githubusercontent.com/711940/30557370-4c4fa756-9cae-11e7-9ca3-1ffb9c877ba3.png)

**Comment by mallowigi** [comment]
I see. In Appearance, you should see the font you're using. It should be "Roboto - 12" if you unchecked the checkbox.

If you checked the box and set the font you wanted to, it should persist at each restart.

**Comment by mallowigi** [comment]
lol I'm getting weird bugs when going back from a bigger font to the default one, but it's not relevant with the theme ;)

**Comment by sebastiaanluca** [comment]
Yeah, just noticed the theme/plugin comes with Roboto by default. It doesn't render all that well on my screen and in that size. I've set it back to the default (I think?) now:

![screen shot 2017-09-18 at 20 23 48](https://user-images.githubusercontent.com/711940/30557691-69718092-9caf-11e7-8ae3-31a8e892098f.png)

Only issue now is that is resets to 12pt after each restart. Font stays the same.

**Comment by mallowigi** [comment]
It shouldn't be. I just checked and after restart the font size is kept;

And Roboto rocks!

**Comment by sebastiaanluca** [comment]
Anything I can do to debug this issue on my machine? Tried it a few times, always resets the font size to 12 (the default).

And sure, I use it in designs from time to time, but I prefer applications to use the default system font otherwise I'd be going nuts 🙃  Also barely readable at 12pt on my screen.

**Comment by DioDread** [comment]
@mallowigi Hello, I get such error on WebStorm 
"Unable to save plugin settings: The plugin com.chrisrm.idea.MaterialThemeUIFork failed to save settings and has been disabled. Please restart WebStorm"
Can you please tell how to fix that?)

**Comment by mallowigi** [comment]
do you have the latest EAP installed? There was an issue with the color schemes when updating to the 2017.3 EAP, basically any custom color schemes may create this error

https://youtrack.jetbrains.com/issue/IDEA-179174

I've removed the dependency to Darcula in the last update, but if you have custom Color Schemes you will still have the issue

**Comment by sebastiaanluca** [comment]
No fix?

**Comment by mallowigi** [comment]
As I said, I cannot reproduce this.

**Comment by DioDread** [comment]
@mallowigi all stuff is up to date, I removed custom color or updated color schemes, even updated jetbrains JVM, but attempt to change fonts inside any plugin provided color schemes leads to error.
