### ISSUE TITLE
Whole UI is unreadable

### ISSUE THREAD

**Issue by DarthIwan** [mallowigi/material-theme-jetbrains-eap#172]
### Summary
After installing the plugin everything is unreadable

### Expected behavior
Install the plugin, restart and everything is readable

### Actual behavior
After installing and restarting all texts in the UI (except the code self) is unreadable

<img width="333" alt="material_ui_font_issue" src="https://user-images.githubusercontent.com/2246573/30595657-16043f1e-9d52-11e7-8c66-18dff2527365.PNG">

### Environment
WebStorm 2017.2.4
Build #WS-172.4155.35, built on September 11, 2017
Subscription is active until October 4, 2017
JRE: 1.8.0_152-release-915-b11 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

and

IntelliJ IDEA 2017.2.4
Build #IU-172.4155.36, built on September 11, 2017
Subscription is active until October 4, 2017
JRE: 1.8.0_152-release-915-b11 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by mallowigi** [comment]
This is an issue with the Roboto font. Try installing it from Google Fonts and restart the IDE.
