### ISSUE TITLE
Primary font in darker theme is too dark

### ISSUE THREAD

**Issue by josephtaylor** [mallowigi/material-theme-jetbrains-eap#174]
Is it possible to make the font color in the project tree view and menus adjustable? Somewhere along the line in the updates it has gotten way too dark and too similar to the background for me to read.

**Comment by mallowigi** [comment]
This is the color used in the Sublime plugin. This will not change, but you can still adjust your own colors using the Custom Theme and the Material Custom Theme Colors in the settings and the Material File Colors in the Color Scheme settings
