### ISSUE TITLE
Icons to replace

### ISSUE THREAD

**Issue by mallowigi** [mallowigi/material-theme-jetbrains-eap#179]
List of icons to replace when I have the time:

- Structure tool window
- Scopes

**Comment by mallowigi** [comment]
Swift development files

**Comment by dudong0726** [comment]
![image](https://user-images.githubusercontent.com/1704803/31702132-739b3fbc-b407-11e7-875d-e61bae928c59.png)

those icons can be replaced ?

**Comment by mallowigi** [comment]
With what?

**Comment by mallowigi** [comment]
Travis configuration files
