### ISSUE TITLE
Feature poll: Bigger icons ?

### ISSUE THREAD

**Issue by mallowigi** [mallowigi/material-theme-jetbrains-eap#181]

**Comment by gencer** [comment]
bigger icons -for what part exactly? Are we talking on File Icons that sidebar and top bar have? No. It will look like a big head starring at us. Just saying. :) Or mayb, If we can have some demo screenshot that illustrates what's exactly bigger icons will look like, would be awesome.

**Comment by mallowigi** [comment]
Yeah, I'm not sure about that either... I thought maybe for accessibility purposes, but I think HiDPi screens are fine, aren't they? Need to check...
