### ISSUE TITLE
Disable folder colors in project view when viewing a file

### ISSUE THREAD

**Issue by Arliee** [mallowigi/material-theme-jetbrains-eap#185]
It seems that after installing this plugin, the IDE now colors folders in the project view based on whether a file inside of that folder is currently open or not.  I personally only want folders to be colored if one of their descendants is changed in version control (which is what it did before I installed the plugin).

Is there an option to configure/disable this functionality?  I'm not sure if this is an enhancement request or just an option that already exists somewhere in the settings that I'm missing.

**Comment by mallowigi** [comment]
Nope, there is no such thing. If you want to develop it, be my guest, but it is not on the roadmap.
