### ISSUE TITLE
Window headers aren't changed in latest EAP

### ISSUE THREAD

**Issue by roboslone** [mallowigi/material-theme-jetbrains-eap#186]
![screenshot](https://user-images.githubusercontent.com/1941275/31286191-1146540e-aac6-11e7-9971-b7792e3af89f.png)

Also, since I'm writing about this kind of windows, is that possible to remove that light line on top (or make it optional)? I believe that line is there because it's in Material guidelines, but it really doesn't look good in IDEA:
![screenshot2](https://user-images.githubusercontent.com/1941275/31286472-e5e8c890-aac6-11e7-923e-9629b1a4e418.png)

### Environment
PyCharm 2017.3 EAP (Professional Edition)
Build #PY-173.2941.3, built on October 3, 2017
PyCharm EAP User
Expiration date: November 2, 2017
JRE: 1.8.0_152-release-1012-b1 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6

**Comment by mallowigi** [comment]
Fixed

**Comment by roboslone** [comment]
Thanks!

But what about that line on top?

**Comment by mallowigi** [comment]
I don't know but either way I'm not adding features at the moment.
