### ISSUE TITLE
Ignored folders text difficult to read

### ISSUE THREAD

**Issue by renestalder** [mallowigi/material-theme-jetbrains-eap#188]
### Summary

Contrast of ignored folders font color to its background color is too low and difficult to read.

### Expected behavior

No background color or darker background color. Brighter font color.

### Actual behavior

Just... hard to read.

![screen shot 2017-10-13 at 09 12 47](https://user-images.githubusercontent.com/105358/31534441-3e37f702-aff7-11e7-9529-666b6f910e2b.png)

### Environment

to the clipboard and paste it here.
PhpStorm 2017.2.4
Build #PS-172.4155.41, built on September 15, 2017
Licensed to ************
Subscription is active until ************
JRE: 1.8.0_152-release-915-b11 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13

**Comment by mallowigi** [comment]
Read the README

**Comment by renestalder** [comment]
Thanks. I'm going to put that here for everyone having the same problem and doesn't read the README with every update:

> Material Status File Colors
> 
> Since the latest releases IntelliJ IDEA removed the option to set colors to specific file statuses (added to VCS, modified, ignores...). This plugin is giving the opportunity to set it back, but only in the Project Tree.
> 
> You can find the settings to set the file colors under Colors and Fonts -> Material File Colors. Of course, this is per color scheme, not per theme, so please take this into consideration.
> 
> Note: Jetbrains added back the File Colors under Version Control > File Status Colors. This is something rather new from 2017 .3 so for now the plugin ignores these settings and uses the Material File Colors settings instead, but it could change in the future.

**Comment by mallowigi** [comment]
Sorry for being rude, but there are some questions that are always recurring all the time. Since closed issues are pretty hard to keep track on, currently there is no way to answer all troubleshooting questions other than updating the README.

I'm working on a documentation at the moment, I hope that will solve all answers!
