### ISSUE TITLE
Text in database table edit dialog is not readable

### ISSUE THREAD

**Issue by loolooyyyy** [mallowigi/material-theme-jetbrains-eap#189]
### Summary
Text in database table edit dialog is not readable.

### Expected 
Text color must be light (white?)

### Actual behavior
Text is black, so is the background.

### Steps to reproduce (if needed)

1. Create a data source in database view.
2. Connect to a sample database with some tables.
3. List the database's tables
4. Choose any table, right click and in the context menu choose `Modify table (Ctrl + F6)`
5. Dialog will open and the table's column names are not readable.

![untitled](https://user-images.githubusercontent.com/3070413/31574145-6746cf3a-b0d6-11e7-913f-4bb2c507e921.png)

### Environment

Color blind filter is turned *off*

IntelliJ IDEA 2017.2.5
Build #IU-172.4343.14, built on September 26, 2017
Licensed to milan

JRE: 1.8.0_152-release-915-b12 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.13.4-200.fc26.x86_64

**Comment by loolooyyyy** [comment]
Oh and for the curious eyes, the DB design is not mine, I wouldn't make such a mess. I'm actually migrating it :laughing:

**Comment by mallowigi** [comment]
You aren't using the Material Color Scheme apparently.
