### ISSUE TITLE
Ability to change font size in auto-complete box

### ISSUE THREAD

**Issue by gencer** [mallowigi/material-theme-jetbrains-eap#190]
### Summary

Ability to change font size in auto-complete box.

### Expected behavior

We should be able to change font-size for auto-complete list. I preferably choose larger font size for IntelliSense items in VS and IntelliJ (JetBrains). I would offer this to JetBrains and I am sure they will add such behavior but i doubt anything near. So, as you alter many settings, I would like to try my chance here and maybe we can get for beta/test faster than them.

### Actual behavior

When typing, suggestion box comes as auto-complete feature and it's font family and size are the same as editor's.

**Comment by mallowigi** [comment]
What are you saying, they will probably NOT do it. They have no plans of developing more customization to the UI and the IntelliSense is something that works and wasn't touched in years.

But I can probably do what you request, but it will not happen until... for some time :) I have plenty of work to do and cannot concentrate on adding new features. And I need to finish the doc first.
