### ISSUE TITLE
The last version is incompatible with this installation?

### ISSUE THREAD

**Issue by XavierCLL** [mallowigi/material-theme-jetbrains-eap#191]
I have the 1.0.0 version of Material theme UI EAP, the last version 1.1.0 not show for update in the plugins list inside Pycharm, and when I try install it manually using the zip downloaded from jetbrain plugin page, it say:

Error:
Plugin 'Material Theme UI EAP' is incompatible with this installation

* Archlinux 64bit
* Pycharm professional 2017.2

**Comment by mallowigi** [comment]
Yep it's only for 2017.3 and over. I am not done with it so I'm focusing on fixing issues on latest EAP. I will release the version to the main repo after that.
