### ISSUE TITLE
No syntax highlighting for colors in xml

### ISSUE THREAD

**Issue by aksh1618** [mallowigi/material-theme-jetbrains-eap#193]
### Summary

Color declarations and references in xml files Android Studio are not highlighted, they are just grey. This behaviour is present in declaration in values/colors.xml as well as reference in any other xml such as layout, drawable, style etc. This issue appeared some time (2 to 3 weeks) ago, but I ignored it as a canary bug. However, this issue is still present on Android Studio 3.1 Canary 2, and only for color schemes of this plugin

### Expected behavior

Proper syntax highlighting of statements involving colors:
`<color name="colorPrimary">#3F51B5</color>`
`<item name="colorPrimary">@color/colorPrimary</item>`
`"@color/colorAccent"`
`"@android:color/black"`

### Actual behavior

They are grey or "inactive"

![matthemecolor](https://user-images.githubusercontent.com/26065812/32403859-6c438e5c-c16a-11e7-85d0-9c64f1e82eeb.png)
![matthemecolor2](https://user-images.githubusercontent.com/26065812/32403860-6c944ae0-c16a-11e7-8eb8-7aefa80893fa.png)
![matthemecolor3](https://user-images.githubusercontent.com/26065812/32403861-6cd91cd8-c16a-11e7-8b14-f905614db94a.png)

### Environment

Plugin Version: 1.1.2.pre
Android Studio 3.1 Canary 2
Build #AI-171.4429293, built on November 2, 2017
JRE: 1.8.0_152-release-1012-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by mallowigi** [comment]
Yes, I've concluded this as well. It happens also on color values in css/scss files. Wonder why

**Comment by mallowigi** [comment]
Ok I think I've found the issue. A fix is on the way

**Comment by aksh1618** [comment]
@mallowigi Still present in 1.2.1-pre

**Comment by mallowigi** [comment]
Have you reseted the color scheme?

--
Elior

**Comment by aksh1618** [comment]
@mallowigi If by resetting you mean setting color scheme to default and back, then yes. Or is something else required?

**Comment by aksh1618** [comment]
@mallowigi I'm not sure if it helps, but the formatting disappears on completion of inspection as soon as the color previews (those little squares) appear.

**Comment by mallowigi** [comment]
![image](https://user-images.githubusercontent.com/5015756/32702693-5b60ecd0-c7f3-11e7-82a9-ec57ca132e1c.png)

I'm clueless.

BTW the colorchooser is awesome!

**Comment by mallowigi** [comment]
Oh I think I get it.

**Comment by mallowigi** [comment]
Ok, I've managed to fix this.

Go to the place where your settings are stored (in Windows it's .AndroidStudio3.1, see README for more info), inside config/colors. If you see your color schemes copy "@_user_...", just remove them after you've closed the application. Restart and if you have the original color schemes you should see the highlighting.

**Comment by aksh1618** [comment]
Yes, that worked. I should get better at reading READMEs, especially the parts marked 'Important' 😅
