### ISSUE TITLE
Seperate icon for groups

### ISSUE THREAD

**Issue by gayanper** [mallowigi/material-theme-jetbrains-eap#194]
### Summary
Today the same icon is used for both projects and groups

### Expected behavior

Separate icon for groups so that the project and group can be differentiated in project view.

### Actual behavior

The same icon is used for both projects and groups

### Steps to reproduce (if needed)

Open a project which has project group configured.

### Environment
IntelliJ IDEA 2017.2.6
Build #IC-172.SNAPSHOT, built on 09:33, November 6, 2017
JRE: 1.8.0_152-release-915-b12 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

Plugin version : Version: 1.1.2.pre

**Comment by mallowigi** [comment]
How do i configure groups ?

**Comment by gayanper** [comment]
https://www.jetbrains.com/help/idea/grouping-modules.html
![image](https://user-images.githubusercontent.com/7471994/32558448-c4902a1c-c4ca-11e7-80d9-6c41e2e8a394.png)

**Comment by mallowigi** [comment]
I cannot manage to make it work somehow. Anyway I'd prefer if you'd do a PR since I have no time to make it work nor choose the right icon.

Icons are at https://materialdesignicons.com/

Closing this PR
