### ISSUE TITLE
Theme option for compact tables rows and list rows

### ISSUE THREAD

**Issue by gayanper** [mallowigi/material-theme-jetbrains-eap#195]
### Summary
Theme option for compact tables rows and list rows because some time the default height for lists and tables are too large and wast lot of space.

### Expected behavior
Ability to set the height of list and table items or a toggle to switch between compact mode (the default height from the Dracula theme) and normal material mode.

### Steps to reproduce (if needed)

1. Open Module settings dependencies tab or subversion log
2. row height is too large which wast lot of space.

### Environment
IntelliJ IDEA 2017.2.6
Build #IC-172.SNAPSHOT, built on 09:33, November 6, 2017
JRE: 1.8.0_152-release-915-b12 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

Plugin version : Version: 1.1.2.pre

**Comment by mallowigi** [comment]
It would be great if you can do it yourself :) 

I'll plan it for a future release

**Comment by gayanper** [comment]
By the way i found it

**Comment by mallowigi** [comment]
Please use the main repository for this.
