### ISSUE TITLE
Darker theme file/folder "disabled" foreground color contrast with .ignore plugin

### ISSUE THREAD

**Issue by nazrhyn** [mallowigi/material-theme-jetbrains-eap#196]
### Summary
Compared to the Darkula theme...   
![image](https://user-images.githubusercontent.com/1672405/32553782-cfba4ec8-c465-11e7-9fea-9be8ff2edd25.png)

...the difference between the foreground color of a "disabled" file or folder and the normal file/folder foreground color is hard to discern.   
![image](https://user-images.githubusercontent.com/1672405/32554462-dd1ed8b6-c467-11e7-8a7f-fb5315d21809.png)

In both of these examples, **.editorconfig** has been added to **.gitignore**. The [**.ignore**](https://github.com/hsz/idea-gitignore) plugin "grays out" the filename to indicate this. I _feel_ like there are other things in the base UI that also gray out files or folders, but I can't find one at the moment, so I'm using this as the example. In this case the grayed-out color is actually _lighter_ than the default file color.

I've looked around in the settings and also in your README (since I've failed at that, before) and I can't find anywhere where the foreground color of project files can be customized. I'm not sure if you think this is your problem or the **.ignore** plugin's problem, but I figured I'd start here.

### Expected behavior
Either **(1)** the default file color is brighter in the Darker theme (IMO it's pretty dark) or **(2)** it's possible to configure the project file foreground colors.

### Actual behavior
The two colors are very close.

### Environment
WebStorm 2017.2.5
Build #WS-172.4343.25, built on October 20, 2017
JRE: 1.8.0_152-release-915-b12 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.10.0-38-generic

Material Theme UI EAP 1.2.1-pre
Configuration: https://gist.github.com/nazrhyn/b005065d2ba1ca58dc64f9beb950f2e6

.ignore 2.3.0

------
P.S. :wave: Hello again!

**Comment by nazrhyn** [comment]
It looks like the custom theme thing _should_ let me modify this, but I haven't been able to find the right thing to change in there...

Speaking of that, though, just clicking onto and off of that configuration page makes it think it has changed.   
![customtheme](https://user-images.githubusercontent.com/1672405/32564658-f8b14486-c482-11e7-8e62-850b952ffe6a.gif)

I've seen some other strange behavior in there, too, but it hasn't persisted since wiped my settings files and let it recreate them.

**Comment by mallowigi** [comment]
Yeah there are some odd stuff with the gitignore plugin, recently I’ve changed the color to brown but it doesn’t work every time, and I’m not even sure that this is a good color anyway.

**Comment by mallowigi** [comment]
Also you should be able to configure this from the color scheme’s material file colors

**Comment by nazrhyn** [comment]
As far as I've understood the File Colors, they're _just_ background colors -- not foreground.

**Comment by mallowigi** [comment]
I’m talking about the color scheme’s file colors. It is under `Editor -> Color Scheme -> Material File Colors`

**Comment by nazrhyn** [comment]
Oh, what the heck. I didn't even know this was here...

![image](https://user-images.githubusercontent.com/1672405/32661876-818c0042-c5f6-11e7-9778-b5432dd943ad.png)

Looks like that will do it. It seems like every other time I open an issue here, I find out there's something I've been missing this whole time :blush:.

Thanks!
