### ISSUE TITLE
un-focused file highlight is blue in Darker theme

### ISSUE THREAD

**Issue by nazrhyn** [mallowigi/material-theme-jetbrains-eap#198]
_I noticed this one while I was testing the file color changes for #196._

------

### Summary
I'm not sure you consider this to be an issue, but I thought I'd point it out anyway. Here are my file colors settings:   
![image](https://user-images.githubusercontent.com/1672405/32662454-9a15b3d6-c5f8-11e7-82dc-f4db61408d8a.png)

Here you can see the un-focused highlight:   
![blurred-file](https://user-images.githubusercontent.com/1672405/32662471-a7da79d4-c5f8-11e7-8400-138b6ed3b91d.gif)

### Expected behavior
From our previous conversations, it seems like the intention for Darker is to not use any of those blue colors; so, I'd expect this to be a shade of gray.

### Actual behavior
Blue.

### Environment
WebStorm 2017.2.5
Build #WS-172.4343.25, built on October 20, 2017
JRE: 1.8.0_152-release-915-b12 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.10.0-38-generic

Material Theme UI EAP 1.2.1-pre
Configuration: https://gist.github.com/nazrhyn/b005065d2ba1ca58dc64f9beb950f2e6

**Comment by mallowigi** [comment]
https://github.com/ChrisRM/material-theme-jetbrains/issues/466
