### ISSUE TITLE
Scaling Support?

### ISSUE THREAD

**Issue by j9ac9k** [mallowigi/material-theme-jetbrains-eap#2]
Hi,

Love the extension, thanks for making/maintaining it.  This may not be where the fault is, but I was hopping that support for HiDPI screens could be implemented.  As it stands now, each time I start PyCharm with the material theme, I need to increase the font significantly to make it usable (this needs to be done at each restart of PyCharm), whereas the default color scheme has the font scale accordingly.

The font that is small is just the editor font.

I don't know how PyCharm plugins work, so this may be outside the scope.

Thanks

**Comment by mallowigi** [comment]
I don't see what you mean, I also have a HiDPi screen and the editor looks ok. I'm on Windows 10 with 3580 * 2540 with 225% scale

Can you post me a screenshot of what it looks like and what specs are you using?

**Comment by j9ac9k** [comment]
Sorry, I meant to post screenshots originally, found myself in a rush, I should have known better than to not include them to begin with.

This is what PyCharm looks for me when I enable the theme or just launch pycharm. 

![image](https://cloud.githubusercontent.com/assets/646398/24411713/6358795c-138b-11e7-8631-4478820aadc8.png)

I can make the text large enough to read by upping the font a bunch (the lines are artifacts of the screen shot tool I'm using), but that setting does not persist during a quit/open of PyCharm.

By contrast, this is what it looks like with default theme settings (when I just switch to them or load it up)

![image](https://cloud.githubusercontent.com/assets/646398/24411857/bc05b5ba-138b-11e7-84da-cd0088ec50ad.png)

For reference, I'm on Linux (arch) using PyCharm CE 2017.1, on a dell XPS 15 with a 3200x1800 resolution screen. 

There could definitely be a setting I'm missing in PyCharm, I haven't been using it all that long.

Thanks!

**Comment by mallowigi** [comment]
Well unfortunately I can't reproduce this behavior, so I'd suggest you to submit me a PR with the fix and I'll merge it. Thanks!
