### ISSUE TITLE
Cannot enable light theme

### ISSUE THREAD

**Issue by xasx** [mallowigi/material-theme-jetbrains-eap#202]
Disclaimer: Somehow, I feel like being too stupid to get me a light Material look and feel. 😕 
Please just advice the correct steps if possible. ❤️ 

### Summary

Cannot enable the lighter variant of the Material Theme in IDEA.

### Expected behavior

I get an IDE as documented with the Screenshots seen in the READMEs here.

### Actual behavior

The theme is always reset to dark.

### Steps to reproduce

1. Select the Editor Color Scheme ' Material Lighter'
2. Apply and also Activate the Light IDE theme by accepting the popped up dialog
3. Notice that the tree views still have dark background
4. Restart IDEA

The intermediate state before restarting looks like 
![idea64_2017-11-12_13-26-22-04e1a1f5](https://user-images.githubusercontent.com/1582730/32698922-6e08fd46-c7ad-11e7-8ca0-49ace0372717.png)

### Environment
```
IntelliJ IDEA 2017.3 EAP (Ultimate Edition)
Build #IU-173.3622.25, built on November 9, 2017
IntelliJ IDEA EAP User
Expiration date: December 9, 2017
JRE: 1.8.0_152-release-1038-b6 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

**Comment by mallowigi** [comment]
Which plugin version? I've just checked and it works good (not EAP)

**Comment by xasx** [comment]
It is EAP, version `1.3.0-beta5` (latest I could get).

**Comment by mallowigi** [comment]
Please dl the last version and tell me if it reproduces

**Comment by xasx** [comment]
Still no difference with this issue.

The logs do not reveal anything critical AFAICS. I attached it anyway, it is a fresh one from only performing the steps from above.
[idea.log](https://github.com/mallowigi/material-theme-jetbrains-eap/files/1464969/idea.log)


However, I noticed you brought the progress bars back 👍

**Comment by mallowigi** [comment]
You're talking about the Light Custom Theme or the Lighter Theme?

**Comment by xasx** [comment]
The Lighter Editor Color Scheme.

What is the Light Custom Theme? The thing that gets activated after the dialog is being confirmed?

**Comment by xasx** [comment]
The dialog I am talking about is this one:
![idea64_2017-11-12_19-32-48-5a394f42](https://user-images.githubusercontent.com/1582730/32702017-6b468438-c7e0-11e7-9994-18620de860c2.png)

**Comment by xasx** [comment]
Confirming with yes, these settings can be found under Material Custom Theme:

![idea64_2017-11-12_19-42-58-7055a192](https://user-images.githubusercontent.com/1582730/32702099-c7a0b40a-c7e1-11e7-89bc-be1d9e66d367.png)

**Comment by mallowigi** [comment]
If you change the color scheme, IDEA will ask you if you want to change the **Look And Feel** of the application, without changing the **Material Theme**.

I don't know what steps you used but do the following:
1. Open the Quick Switch (Ctrl+~)
2. In Material Theme, select "Lighter Theme"
3. Switch the color scheme to Lighter as well
4. If the IDEA popup appears, click "NO"
5. Restart if necessary

**Comment by xasx** [comment]
Thanks, I did thing the settings were the primary interface.

I'll experiment a bit.

BTW: The 'All actions' (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>A</kbd>) also allowed me to turn the Lighter theme on.
