### ISSUE TITLE
Default values for code coverage should be change to neutral colors ?

### ISSUE THREAD

**Issue by bernalrs** [mallowigi/material-theme-jetbrains-eap#26]
Hi,

When I launch the code coverage tool in PyCharm the default background colours for coverage are very aggressive.  These can be tweaked manually in settings > Editor > Colors & Fonts >General > Line Coverage > (Full, Uncovered) Background however it would it would be best to include more neutral colours within the plugin itself. 

Thanks

**Comment by mallowigi** [comment]
should be fixed
