### ISSUE TITLE
Event Log popups do not have theme

### ISSUE THREAD

**Issue by gbaldeck** [mallowigi/material-theme-jetbrains-eap#33]
I'm using version 0.3.7 with the default theme in IntelliJ 2017.1.3. I noticed this is the previous version of the plugin also. An image of the issue is below.

I seem to remember the bottom right Event Log popups having the same theme colors (correct me if I'm wrong). But now they are taking the colors of my chosen IntelliJ Theme, in this case Darcula.

![image](https://cloud.githubusercontent.com/assets/4185224/26276769/860adbf4-3d32-11e7-82e2-7c4f4bbde284.png)

**Comment by mallowigi** [comment]
Yeah notification popups are not themed. I will take care of it at some point.

**Comment by mallowigi** [comment]
I've themed them to look like popups from material design
