### ISSUE TITLE
When running certain terminal commands console output is broken

### ISSUE THREAD

**Issue by Stefan-Aurea** [mallowigi/material-theme-jetbrains-eap#35]
This applies to a Windows installation, though have not tested it on others.

Version: 0.3.7.1

Sample output:
![image](https://cloud.githubusercontent.com/assets/22632893/26356324/0027fd0e-3fcc-11e7-8cab-31abdb67fa41.png)

**Comment by mallowigi** [comment]
Dont see what's wrong here. Can you check again with latest version?

**Comment by Stefan-Aurea** [comment]
If you look at the bottom part, there is a space between the prompt and the actual cursor, and part of the prompt is actually shown on the right hand side.

Though you are correct, this does not seem to be an issue with the latest version after I updated.

**Comment by mallowigi** [comment]
oh cool
