### ISSUE TITLE
select/combobox after-focus issue

### ISSUE THREAD

**Issue by nazrhyn** [mallowigi/material-theme-jetbrains-eap#36]
![image](https://cloud.githubusercontent.com/assets/1672405/26375090/8f8a0bb4-3fd5-11e7-8884-1a87bc086326.png)

After a select/combobox is focused and then blurred, this effect on the down-arrow box happens. I tried on both Default and Darker themes and, while the effect is more visible in Darker, it exists in both.

Thanks!

**Comment by mallowigi** [comment]
Okay I see what's happening. It's because the caret is acting like a button, so it gets the background on hover change.

Still, it's a minor issue so I will look at some point but its' not important.

**Comment by nazrhyn** [comment]
:+1:
