### ISSUE TITLE
Oh React icon, wherefore art thou React Icon?!

### ISSUE THREAD

**Issue by zeg-io** [mallowigi/material-theme-jetbrains-eap#38]
It is with great sadness that I opened my React project only to find that all my .jsx files now had an ... "improved" icon rather than my non-scientifically-correct model of an atom that passes for the React logo.

Is there a reason for this?  I specifically had used that extension to differentiate my code more with the icon. :/

Great work on the rest though!  :D

**Comment by mallowigi** [comment]
Yup, the reason is this: https://github.com/ihodev/a-file-icon

Icons are taken from this repository.

In the future I will find a way to use icons defined in "File Types" settings, but for now bear with it :/

**Comment by zeg-io** [comment]
I reached out to them, seems like it is at least being considered! :)

**Comment by mallowigi** [comment]
great! TBH I need to follow after this repository to add new icons as soon as they are available :)

**Comment by mallowigi** [comment]
Hey @zeg-io 

I decided to include your icon :) However since it is not available in the aforementioned repo, I need someone to design the icons.

Can you make these icons? It needs to be 16x16 and 32x32.

Thanks

**Comment by zeg-io** [comment]
Sure! I'll dink with it later tonight.

**Comment by mallowigi** [comment]
Actually never mind I find a way to do it :)

**Comment by mallowigi** [comment]
Closing this. This will be available on the next release in a few days.

**Comment by zeg-io** [comment]
@mallowigi I got the 0.4.1 release... no icon :(

**Comment by mallowigi** [comment]
Yeah don't worry icons are coming

**Comment by zeg-io** [comment]
Awesome, thank you!
