### ISSUE TITLE
exception

### ISSUE THREAD

**Issue by huangsizhou** [mallowigi/material-theme-jetbrains-eap#39]
It's prohibited to access index during event dispatching java.lang.Throwable 	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132) 	at com.intellij.openapi.project.NoAccessDuringPsiEvents.checkCallContext(NoAccessDuringPsiEvents.java:38) 	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:666) 	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:646) 	at com.intellij.psi.stubs.StubIndexImpl.a(StubIndexImpl.java:335) 	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:316) 	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:145) 	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:134) 	at com.intellij.psi.impl.java.stubs.index.JavaFullClassNameIndex.get(JavaFullClassNameIndex.java:48) 	at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.doFindClasses(JavaFileManagerImpl.java:96) 	at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.findClass(JavaFileManagerImpl.java:131) 	at com.intellij.psi.impl.PsiElementFinderImpl.findClass(PsiElementFinderImpl.java:54) 	at com.intellij.psi.impl.JavaPsiFacadeImpl.doFindClass(JavaPsiFacadeImpl.java:131) 	at com.intellij.psi.impl.JavaPsiFacadeImpl.findClass(JavaPsiFacadeImpl.java:108) 	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:405) 	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.access$100(PsiJavaCodeReferenceElementImpl.java:55) 	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:360) 	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:352) 	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$1(ResolveCache.java:185) 	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112) 	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:184) 	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:721) 	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:713) 	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.multiResolve(PsiJavaCodeReferenceElementImpl.java:387) 	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.advancedResolve(PsiJavaCodeReferenceElementImpl.java:380) 	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:349) 	at com.intellij.psi.impl.source.PsiImportStatementBaseImpl.resolve(PsiImportStatementBaseImpl.java:64) 	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.processDeclarationsNoGuess(PsiJavaFileBaseImpl.java:331) 	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.access$100(PsiJavaFileBaseImpl.java:54) 	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl$MyCacheBuilder.compute(PsiJavaFileBaseImpl.java:542) 	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49) 	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222) 	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60) 	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38) 	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.processDeclarations(PsiJavaFileBaseImpl.java:300) 	at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:69) 	at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:51) 	at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:218) 	at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:149) 	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:458) 	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.access$100(PsiJavaCodeReferenceElementImpl.java:55) 	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:360) 	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:352) 	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$1(ResolveCache.java:185) 	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112) 	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:184) 	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:721) 	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:713) 	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.multiResolve(PsiJavaCodeReferenceElementImpl.java:387) 	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.advancedResolve(PsiJavaCodeReferenceElementImpl.java:380) 	at com.intellij.psi.impl.source.PsiClassReferenceType.resolveGenerics(PsiClassReferenceType.java:184) 	at com.intellij.psi.impl.source.PsiClassReferenceType.resolve(PsiClassReferenceType.java:131) 	at com.intellij.psi.util.TypeConversionUtil$2.visitClassType(TypeConversionUtil.java:1266) 	at com.intellij.psi.util.TypeConversionUtil$2.visitClassType(TypeConversionUtil.java:1257) 	at com.intellij.psi.PsiClassType.accept(PsiClassType.java:230) 	at com.intellij.psi.util.TypeConversionUtil.erasure(TypeConversionUtil.java:1257) 	at com.intellij.psi.util.TypeConversionUtil.erasure(TypeConversionUtil.java:1251) 	at com.intellij.debugger.engine.JVMNameUtil.a(JVMNameUtil.java:92) 	at com.intellij.debugger.engine.JVMNameUtil.a(JVMNameUtil.java:354) 	at com.intellij.debugger.engine.JVMNameUtil.getJVMSignature(JVMNameUtil.java:327) 	at com.intellij.debugger.ui.breakpoints.MethodBreakpoint$3.compute(MethodBreakpoint.java:466) 	at com.intellij.debugger.ui.breakpoints.MethodBreakpoint$3.compute(MethodBreakpoint.java:444) 	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:942) 	at com.intellij.debugger.ui.breakpoints.MethodBreakpoint.a(MethodBreakpoint.java:444) 	at com.intellij.debugger.ui.breakpoints.MethodBreakpoint.reload(MethodBreakpoint.java:107) 	at com.intellij.debugger.ui.breakpoints.BreakpointWithHighlighter.reload(BreakpointWithHighlighter.java:242) 	at com.intellij.debugger.ui.breakpoints.BreakpointManager.fireBreakpointChanged(BreakpointManager.java:599) 	at com.intellij.debugger.ui.breakpoints.BreakpointManager$2.breakpointChanged(BreakpointManager.java:144) 	at sun.reflect.GeneratedMethodAccessor717.invoke(Unknown Source) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:498) 	at com.intellij.util.EventDispatcher.dispatch(EventDispatcher.java:99) 	at com.intellij.util.EventDispatcher.access$200(EventDispatcher.java:35) 	at com.intellij.util.EventDispatcher$2.invoke(EventDispatcher.java:79) 	at com.sun.proxy.$Proxy76.breakpointChanged(Unknown Source) 	at com.intellij.xdebugger.impl.breakpoints.XBreakpointManagerImpl.fireBreakpointChanged(XBreakpointManagerImpl.java:169) 	at com.intellij.xdebugger.impl.breakpoints.XBreakpointBase.fireBreakpointChanged(XBreakpointBase.java:118) 	at com.intellij.xdebugger.impl.breakpoints.XLineBreakpointImpl.setFileUrl(XLineBreakpointImpl.java:266) 	at com.intellij.xdebugger.impl.breakpoints.XLineBreakpointManager$1.fileUrlChanged(XLineBreakpointManager.java:96) 	at com.intellij.openapi.vfs.VirtualFileUrlChangeAdapter.fileMoved(VirtualFileUrlChangeAdapter.java:28) 	at sun.reflect.GeneratedMethodAccessor984.invoke(Unknown Source) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:498) 	at com.intellij.util.EventDispatcher.dispatch(EventDispatcher.java:99) 	at com.intellij.util.EventDispatcher.access$200(EventDispatcher.java:35) 	at com.intellij.util.EventDispatcher$2.invoke(EventDispatcher.java:79) 	at com.sun.proxy.$Proxy19.fileMoved(Unknown Source) 	at com.intellij.openapi.vfs.impl.BulkVirtualFileListenerAdapter.fireAfter(BulkVirtualFileListenerAdapter.java:89) 	at com.intellij.openapi.vfs.impl.BulkVirtualFileListenerAdapter.after(BulkVirtualFileListenerAdapter.java:56) 	at sun.reflect.GeneratedMethodAccessor146.invoke(Unknown Source) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:498) 	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117) 	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:437) 	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:398) 	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:387) 	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:373) 	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:44) 	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:230) 	at com.sun.proxy.$Proxy153.after(Unknown Source) 	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.processEvents(PersistentFSImpl.java:779) 	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.a(PersistentFSImpl.java:676) 	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.moveFile(PersistentFSImpl.java:672) 	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.a(VirtualFileSystemEntry.java:268) 	at com.intellij.openapi.vfs.encoding.EncodingRegistry.doActionAndRestoreEncoding(EncodingRegistry.java:70) 	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.move(VirtualFileSystemEntry.java:267) 	at com.intellij.refactoring.move.moveFilesOrDirectories.MoveFilesOrDirectoriesUtil.doMoveFile(MoveFilesOrDirectoriesUtil.java:92) 	at com.intellij.refactoring.move.moveClassesOrPackages.MoveClassesOrPackagesUtil.doMoveClass(MoveClassesOrPackagesUtil.java:239) 	at com.intellij.refactoring.move.moveClassesOrPackages.MoveClassesOrPackagesProcessor.performRefactoring(MoveClassesOrPackagesProcessor.java:504) 	at com.intellij.refactoring.BaseRefactoringProcessor.a(BaseRefactoringProcessor.java:487) 	at com.intellij.refactoring.BaseRefactoringProcessor.a(BaseRefactoringProcessor.java:498) 	at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:985) 	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176) 	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556) 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501) 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66) 	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163) 	at com.intellij.openapi.progress.util.PotemkinProgress.runInSwingThread(PotemkinProgress.java:167) 	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithProgressInDispatchThread(ApplicationImpl.java:985) 	at com.intellij.refactoring.BaseRefactoringProcessor.a(BaseRefactoringProcessor.java:498) 	at com.intellij.refactoring.BaseRefactoringProcessor.access$100(BaseRefactoringProcessor.java:80) 	at com.intellij.refactoring.BaseRefactoringProcessor$3.run(BaseRefactoringProcessor.java:312) 	at com.intellij.openapi.command.impl.CoreCommandProcessor.a(CoreCommandProcessor.java:149) 	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:109) 	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99) 	at com.intellij.refactoring.BaseRefactoringProcessor.execute(BaseRefactoringProcessor.java:308) 	at com.intellij.refactoring.BaseRefactoringProcessor.doRun(BaseRefactoringProcessor.java:232) 	at com.intellij.openapi.fileEditor.impl.NonProjectFileWritingAccessProvider.disableChecksDuring(NonProjectFileWritingAccessProvider.java:181) 	at com.intellij.refactoring.BaseRefactoringProcessor.run(BaseRefactoringProcessor.java:565) 	at com.intellij.refactoring.ui.RefactoringDialog.invokeRefactoring(RefactoringDialog.java:183) 	at com.intellij.refactoring.move.moveClassesOrPackages.MoveClassesOrPackagesToNewDirectoryDialog.doAction(MoveClassesOrPackagesToNewDirectoryDialog.java:194) 	at com.intellij.refactoring.ui.RefactoringDialog.doRefactorAction(RefactoringDialog.java:88) 	at com.intellij.refactoring.ui.RefactoringDialog$RefactorAction.actionPerformed(RefactoringDialog.java:160) 	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022) 	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348) 	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402) 	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259) 	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252) 	at com.chrisrm.idea.ui.MTButtonUI$1.mouseReleased(MTButtonUI.java:75) 	at java.awt.Component.processMouseEvent(Component.java:6533) 	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) 	at java.awt.Component.processEvent(Component.java:6298) 	at java.awt.Container.processEvent(Container.java:2236) 	at java.awt.Component.dispatchEventImpl(Component.java:4889) 	at java.awt.Container.dispatchEventImpl(Container.java:2294) 	at java.awt.Component.dispatchEvent(Component.java:4711) 	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888) 	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525) 	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466) 	at java.awt.Container.dispatchEventImpl(Container.java:2280) 	at java.awt.Window.dispatchEventImpl(Window.java:2746) 	at java.awt.Component.dispatchEvent(Component.java:4711) 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) 	at java.awt.EventQueue.access$500(EventQueue.java:97) 	at java.awt.EventQueue$3.run(EventQueue.java:709) 	at java.awt.EventQueue$3.run(EventQueue.java:703) 	at java.security.AccessController.doPrivileged(Native Method) 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90) 	at java.awt.EventQueue$4.run(EventQueue.java:731) 	at java.awt.EventQueue$4.run(EventQueue.java:729) 	at java.security.AccessController.doPrivileged(Native Method) 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) 	at com.intellij.ide.IdeEventQueue.k(IdeEventQueue.java:827) 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:651) 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365) 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109) 	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184) 	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229) 	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227) 	at java.security.AccessController.doPrivileged(Native Method) 	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227) 	at java.awt.Dialog.show(Dialog.java:1084) 	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:735) 	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:457) 	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1696) 	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1645) 	at com.intellij.refactoring.move.moveClassesOrPackages.JavaMoveClassesOrPackagesHandler.doMove(JavaMoveClassesOrPackagesHandler.java:146) 	at com.intellij.refactoring.move.MoveHandler.doMove(MoveHandler.java:129) 	at com.intellij.refactoring.move.MoveHandler.invoke(MoveHandler.java:118) 	at com.intellij.ide.projectView.impl.ProjectViewDropTarget$MoveDropHandler.a(ProjectViewDropTarget.java:323) 	at com.intellij.ide.projectView.impl.ProjectViewDropTarget$MoveDropHandler.doDrop(ProjectViewDropTarget.java:302) 	at com.intellij.ide.projectView.impl.ProjectViewDropTarget.b(ProjectViewDropTarget.java:166) 	at com.intellij.ide.projectView.impl.ProjectViewDropTarget.drop(ProjectViewDropTarget.java:133) 	at com.intellij.ide.dnd.DnDManagerImpl$MyDropTargetListener.a(DnDManagerImpl.java:676) 	at com.intellij.ide.dnd.DnDManagerImpl$MyDropTargetListener.drop(DnDManagerImpl.java:651) 	at java.awt.dnd.DropTarget.drop(DropTarget.java:455) 	at sun.awt.dnd.SunDropTargetContextPeer.processDropMessage(SunDropTargetContextPeer.java:538) 	at sun.lwawt.macosx.CDropTargetContextPeer.processDropMessage(CDropTargetContextPeer.java:143) 	at sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchDropEvent(SunDropTargetContextPeer.java:852) 	at sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchEvent(SunDropTargetContextPeer.java:776) 	at sun.awt.dnd.SunDropTargetEvent.dispatch(SunDropTargetEvent.java:48) 	at java.awt.Component.dispatchEventImpl(Component.java:4744) 	at java.awt.Container.dispatchEventImpl(Container.java:2294) 	at java.awt.Component.dispatchEvent(Component.java:4711) 	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888) 	at java.awt.LightweightDispatcher.processDropTargetEvent(Container.java:4599) 	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4461) 	at java.awt.Container.dispatchEventImpl(Container.java:2280) 	at java.awt.Window.dispatchEventImpl(Window.java:2746) 	at java.awt.Component.dispatchEvent(Component.java:4711) 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) 	at java.awt.EventQueue.access$500(EventQueue.java:97) 	at java.awt.EventQueue$3.run(EventQueue.java:709) 	at java.awt.EventQueue$3.run(EventQueue.java:703) 	at java.security.AccessController.doPrivileged(Native Method) 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90) 	at java.awt.EventQueue$4.run(EventQueue.java:731) 	at java.awt.EventQueue$4.run(EventQueue.java:729) 	at java.security.AccessController.doPrivileged(Native Method) 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) 	at com.intellij.ide.IdeEventQueue.k(IdeEventQueue.java:827) 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:651) 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365) 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by huangsizhou** [comment]
the newest version

**Comment by mallowigi** [comment]
ok when is it happening ?
