### ISSUE TITLE
No IDE Theme options

### ISSUE THREAD

**Issue by Gostwow** [mallowigi/material-theme-jetbrains-eap#42]
Hi,

Wanted to change to IDE theme to match the color scheme (Material Darker). The readme says ```To switch the IDE theme (not the code color scheme), go to Tools -> Material Theme and choose one of the new themes.``` but there is simply no such option under ```Tools -> Material Theme```. I can only change tabs boldness, enable  compact sidebar and some other options.

**Comment by mallowigi** [comment]
Oh yeah I get it now why I wrote this. I wasn't talking about the Material Theme Settings but rather to the Tools menu in the main menu.

One day maybe I'll put the selection in the settings but it isn't a priority.

**Comment by Gostwow** [comment]
Oh, thanks for the clarification. Looks so much better now!
