### ISSUE TITLE
Composer.json icon has the wrong size.

### ISSUE THREAD

**Issue by Alexgmin** [mallowigi/material-theme-jetbrains-eap#44]
![image](https://user-images.githubusercontent.com/8340441/26930622-3d6967cc-4c5e-11e7-91d5-acd283604994.png)
![image](https://user-images.githubusercontent.com/8340441/26930645-4f089674-4c5e-11e7-99bd-32af11733ef1.png)

0.4.1 or 0.4.2 broke it.

Edit: PHPStorm also gives me the same error:
`Icon cannot be found in '/icons/plugins/fileTypes/plist.png', aClass='class com.chrisrm.idea.icons.MTFileIconProvider'`

**Comment by ottnorml** [comment]
I'm having the same problem with version 0.4.2.
PhpStorm tells me this error message:
`Icon cannot be found in '/icons/plugins/fileTypes/plist.png', aClass='class com.chrisrm.idea.icons.MTFileIconProvider'`

**Comment by mallowigi** [comment]
should be fixed in the new release.
