### ISSUE TITLE
Oh..what's this....

### ISSUE THREAD

**Issue by xinkunZ** [mallowigi/material-theme-jetbrains-eap#45]
![image](https://user-images.githubusercontent.com/7759897/26959073-d2372568-4d00-11e7-8acd-43bc1cb9265b.png)

I just update version 0.4.3. there have a..um... extra rectangle bar with text "Material Theme - default"... what does this bar use for? And can I remove it?

**Comment by RecallCode** [comment]
I updated also show the status bar, I don't like it, I can remove or disabled it ?

**Comment by mallowigi** [comment]
Oh you didn't like it? :( okay I will make an option to disable it

**Comment by xinkunZ** [comment]
after all there is a change theme button on toolbar, so theme state may be unnecessary I think....
another question is that I found there is a option in settings like [use customer wallpaper], what does this wallpaper use for? I haven't found anywhere used this wallpaper

**Comment by mallowigi** [comment]
Yeah but the toolbar doesn't show you which theme you are on (even though I know that the color should be enough, I thought it would be a nice decorator)

As for the wallpaper, this is the wallpaper set when there is no files opened.

**Comment by xinkunZ** [comment]
![image](https://user-images.githubusercontent.com/7759897/26967858-6c51c5be-4d32-11e7-998a-cb0072bc76bc.png)
Wow! it is so nice !!
