### ISSUE TITLE
Glitches after update to InteliJ Idea 2017.1.4

### ISSUE THREAD

**Issue by KCala** [mallowigi/material-theme-jetbrains-eap#48]
After update to InteliJ Idea 2017.1.4 the IDE glitches in various places. 

This happens both on my Fedora 25 under Wayland and my colleague's Ubuntu 16.04. Glitches happen when the editor theme is set to any of the Material UI schemes. The global IDE theme doesn't affect this (so Idea with Material theme enabled with Darcula set as the editor theme works fine). 

Version: Material Theme UI EAP 0.4.3

Examples of the glitches: 

__Popups render in half__
![screenshot from 2017-06-09 10-31-29](https://user-images.githubusercontent.com/9115622/26967545-f0d46366-4cfe-11e7-96a3-b0eba8179f57.png)

__IDE panels partially stay above editor after being closed__
The dissapear on scroll or window move/resize though
(code blurred)
![screenshot from 2017-06-09 10-35-13](https://user-images.githubusercontent.com/9115622/26967815-eda67a48-4cff-11e7-8795-654dd1b63797.png)

__Editor area is not resized properly when the IDE window is enlarged__
![screenshot from 2017-06-09 10-40-39](https://user-images.githubusercontent.com/9115622/26967903-4f1a649c-4d00-11e7-961d-48499ed088ee.png)

__Even more glitches on window resize__
![screenshot from 2017-06-09 10-42-40](https://user-images.githubusercontent.com/9115622/26967941-7c662cf6-4d00-11e7-911d-93c20b9424dc.png)

_Parts of editor don't refresh properly_
Can't show that on the screenshot without the video but it happens that when you scroll the window with code, some lines don't refresh along with the others. They do after they are clicked directly

**Comment by mallowigi** [comment]
This looks like something related to OpenJDK on Linux. Haven't had any problems on Mac and Windows so I can't tell.

I will try to install a VM and see what I can do.
