### ISSUE TITLE
Question: Can I disable some icons?

### ISSUE THREAD

**Issue by mihailomisic** [mallowigi/material-theme-jetbrains-eap#53]
I like all of the icons in the meterial theme except the `.go` icon. Can I somehow enable/disable certain icons?

_- Sorry for asking the question here I couldn't seem to find a better place to ask this. 
&nbsp;&nbsp; I could not find the solution on my own._

**Comment by mallowigi** [comment]
I can't implement something like this, if you want to put your own icons or disable/add, fork the project and select "import from disk"

**Comment by mihailomisic** [comment]
Oh, ok. Thank you for your time. Keep up the great work! :)
