### ISSUE TITLE
Git branches selector has disappeared from the status bar (bottom right position) after v.0.4.3.2 plugin update

### ISSUE THREAD

**Issue by fatalist** [mallowigi/material-theme-jetbrains-eap#55]
![2017-06-13_132518](https://user-images.githubusercontent.com/313991/27078291-d33ebe92-503b-11e7-9c0f-b0711c9eb2a1.jpg)

**Comment by mallowigi** [comment]
Pardon me for asking but are you sure you have a git repository configured for this project?

![image](https://user-images.githubusercontent.com/5015756/27078910-48ee7ef0-503e-11e7-9a49-bf3efbe7fe8a.png)

**Comment by fatalist** [comment]
Sure! It disappeared after the update.
![2017-06-13_134649](https://user-images.githubusercontent.com/313991/27079063-e14996da-503e-11e7-9f7a-9c45bbc9dfbd.jpg)

**Comment by fatalist** [comment]
You have published two updates tomorrow. I have applied them.

**Comment by mallowigi** [comment]
That's really odd, also, I'm seeing that your "memory indicator" is not themed, so this may be the cause, but for now I can't reproduce it...

**Comment by fatalist** [comment]
This is what I have now
![2017-06-13_140520](https://user-images.githubusercontent.com/313991/27079700-6575378c-5041-11e7-9881-89d7dad53127.jpg)

**Comment by fatalist** [comment]
Also I have tried to reinstall PhpStorm several times from the scrsatch without using the caches and plugins from previous installations, but it doesn't resove the issues.
I use 64-bit launcher with JRE x86 by JetBrains
![2017-06-13_140943](https://user-images.githubusercontent.com/313991/27079842-f83cc8dc-5041-11e7-9661-6fdb4e88dbd7.jpg)

**Comment by mallowigi** [comment]
Nope. No clue why it happens to you... 

![image](https://user-images.githubusercontent.com/5015756/27080007-b844866a-5042-11e7-9a06-c1d5ecd58b80.png)

and I used the same settings as you. 

If you remove the plugin you see the branches ?

**Comment by fatalist** [comment]
> If you remove the plugin you see the branches ?
No. 
I have manually cleaned the PhphStrom installation, then I have installed it again and able to see git branches, but... after new installation of Material Theme UI EAP it breaks status bar again, also I can't change bundled themes, this causes several exceptions.

**Comment by mallowigi** [comment]
Ok can you provide me the plugins you are using? Or does it happen from a  clear install? I really need to know what is causing you this.

**Comment by mallowigi** [comment]
bump

**Comment by MaxyBlack** [comment]
I have the same problem. 
![screenshot from 2017-06-29 16-46-49](https://user-images.githubusercontent.com/2746407/27693766-9bb961c8-5cea-11e7-8176-2450c26873fe.png)

**Comment by mallowigi** [comment]
Can you give me the list of plugins you use ?

**Comment by MaxyBlack** [comment]
yeah, sure
![screenshot from 2017-06-30 09-24-02](https://user-images.githubusercontent.com/2746407/27725318-072975de-5d76-11e7-873b-3376fd8aa77f.png)
![screenshot from 2017-06-30 09-24-44](https://user-images.githubusercontent.com/2746407/27725317-07288b24-5d76-11e7-8d23-9fe9756ae513.png)
![screenshot from 2017-06-30 09-24-59](https://user-images.githubusercontent.com/2746407/27725319-072a22fe-5d76-11e7-8ea2-9d45794662a3.png)

**Comment by mallowigi** [comment]
Try to disable "Code Outline 2" and tell me the results

**Comment by MaxyBlack** [comment]
I removed my old configuration folder and now it looks ok.

**Comment by rolatsch** [comment]
I had the same issue. Disabling "Code Outline 2" solved it for me.
