### ISSUE TITLE
Project opener still use old IntelliJ icon

### ISSUE THREAD

**Issue by Kendos-Kenlen** [mallowigi/material-theme-jetbrains-eap#57]
When browsing to open a project from home screen, IDEA icon used to indicate a project still use the old IJ icon instead of the IDE icon.

![screenshot_20170614_121318](https://user-images.githubusercontent.com/2579741/27127387-2c6c634c-50fb-11e7-95c6-ccb29e78ec2e.png)

**Comment by mallowigi** [comment]
Yeah this is by choice. If you want to change it you can still fork the project and tweak it :)

**Comment by Kendos-Kenlen** [comment]
Can I say it doesn't look good ? :P
Maybe adding an option would be nice :)

**Comment by mallowigi** [comment]
I can't add an option for every icon... You can still disable all MT icons from the settings if you prefer.
