### ISSUE TITLE
Roboto default font without it installed

### ISSUE THREAD

**Issue by nazrhyn** [mallowigi/material-theme-jetbrains-eap#60]
Your recent update changed the default font to Roboto, but I don't actually have that font installed, so all sorts of strange stuff happened (and it looks like it's using Arial).

![image](https://user-images.githubusercontent.com/1672405/27391901-2cf91e5e-5673-11e7-977e-6a71b3045307.png)

Quite a variety of fonts there and font sizes. If Roboto isn't installed, whatever font selection was there previously was significantly better than this mishmash :frowning_face:.

**Comment by nazrhyn** [comment]
After installing Roboto it doesn't look much different, actually; so, I wonder if you were embedding it. The fonts being so inconsistent across the UI as compared to before is definitely a negative, IMO.

![image](https://user-images.githubusercontent.com/1672405/27392146-d741da18-5673-11e7-8006-0803a010c3d0.png)

**Comment by nazrhyn** [comment]
For comparison, this is what it looks like in the base darcula L&F.

![image](https://user-images.githubusercontent.com/1672405/27392326-685e25b0-5674-11e7-97e8-52dc78e2a0d1.png)

**Comment by mallowigi** [comment]
Did you install the right font? https://fonts.google.com/specimen/Roboto?selection.family=Roboto 

I can understand why you wouldn't like it, here is a screen of what it should look like (I disabled the plugin)

![image](https://user-images.githubusercontent.com/5015756/27395177-8fe69f3e-56b7-11e7-8dc9-3e221677ef35.png)

IMO it looks very nice, but if you don't like it, you can still check "Override default fonts" and select "Tahoma" on Windows (for mac I recommend Lucida Grande)

The font you got is probably the default serif font, which is Arial.

**Comment by nazrhyn** [comment]
I installed it from Google fonts, yeah. (Perhaps I need a full system restart rather than just restarting WebStorm afterward?) I guess I just wonder if the default font should be something that many people won't even have installed? Should the Roboto thing be opt-in?

**Comment by mallowigi** [comment]
You have a point, maybe to set the font if it is on the system.

**Comment by nazrhyn** [comment]
It looks like the UI is still falling back to Arial instead of Tahoma (unless I just have some bad leftover settings), or at least something non-default/normal is happening. Some examples:

## Material
![image](https://user-images.githubusercontent.com/1672405/27974950-38c3832e-632e-11e7-8363-986b5ca68f68.png)

![image](https://user-images.githubusercontent.com/1672405/27974964-42ce213a-632e-11e7-8baf-e633bd090e0b.png)

![image](https://user-images.githubusercontent.com/1672405/27974967-46dbed5c-632e-11e7-9fe2-364cf52a9585.png)

## Default
![image](https://user-images.githubusercontent.com/1672405/27975014-7b2793d6-632e-11e7-8af3-d4add35f8003.png)

![image](https://user-images.githubusercontent.com/1672405/27975037-901a756a-632e-11e7-98ab-240697897a51.png)

![image](https://user-images.githubusercontent.com/1672405/27975052-999cdfb0-632e-11e7-8af0-035919dd38a8.png)

I am on 0.4.4 with no updates offered, so maybe you fixed this in 0.5.0?

**Comment by mallowigi** [comment]
0.5.0 are only available for EAPs, sorry :/

Can you settle down with a custom font for the time being?

**Comment by nazrhyn** [comment]
I'm on the EAP version.

![image](https://user-images.githubusercontent.com/1672405/27976775-01a9dc32-6336-11e7-913c-16f7d0ad76d8.png)

That said, anything that means I don't have to look at Arial in my UI (that font is terrible).

**Comment by mallowigi** [comment]
I mean the IDE's EAP

**Comment by mallowigi** [comment]
That said you should really try Roboto :)

**Comment by nazrhyn** [comment]
I will say that I tried installing it on the system, tried restarting the IDE, tried restarting my computer and it always used Arial. Perhaps I should create another issue for that...

**Comment by mallowigi** [comment]
My question would be why you don't receive the update. 

I've published a new version now, tell me if you see it.

**Comment by nazrhyn** [comment]
Just received the update to 0.5.3 and got this on restart:

```
Plugin 'com.chrisrm.idea.MaterialThemeUIFork' failed to initialize and will be disabled.  Please restart WebStorm.

java.lang.IllegalArgumentException: Argument for @NotNull parameter 'theme' of com/chrisrm/idea/MTLaf.<init> must not be null
    at com.chrisrm.idea.MTLaf.$$$reportNull$$$0(MTLaf.java)
    at com.chrisrm.idea.MTLaf.<init>(MTLaf.java)
    at com.chrisrm.idea.themes.MTThemeManager.activate(MTThemeManager.java:156)
    at com.chrisrm.idea.themes.MTThemeManager.activate(MTThemeManager.java:144)
    at com.chrisrm.idea.schemes.MTColorSchemeComponent.activateTheme(MTColorSchemeComponent.java:20)
    at com.chrisrm.idea.schemes.MTColorSchemeComponent.initComponent(MTColorSchemeComponent.java:13)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:491)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:120)
```

Tried turning it back on and restarting and got the same error.

**Comment by mallowigi** [comment]
Yay! So can we close the issue?

**Comment by nazrhyn** [comment]
@mallowigi Haha, yes! Thanks for your patience. Hopefully you don't mind all the input I've given you recently!
