### ISSUE TITLE
Difficult to see the branches in merge change

### ISSUE THREAD

**Issue by ErianSeph** [mallowigi/material-theme-jetbrains-eap#62]
As you can see, the branches are so hard to read with the black font and the black background. Is there a possible solution for this? :)

![image](https://user-images.githubusercontent.com/11443548/27505826-9fe7d878-5877-11e7-93c1-2e39becb9aa8.png)

**Comment by mallowigi** [comment]
Damn it, I see why this happens but I can't understand why this happens! The only way to get the right colors would be to disable the "contrast mode" for tables and I don't want that...

Does that really bother you? If yes then maybe I will add an option to specifically target the contrast mode for tables.

**Comment by ErianSeph** [comment]
No it doesn't really bothers me haha just being lazy to click one branch and navigate through them with the arrow keys to see the text. I was just wondering if there was an easy solution for this, but it seems like it's not so straight forward :(

**Comment by mallowigi** [comment]
Hold on, I might be on to something.

**Comment by mallowigi** [comment]
Nope, no clue. Leaving it open to whoever might be interested in fixing this

**Comment by mallowigi** [comment]
If it bothers too many people then I'll remove contrasted mode on tables

**Comment by mallowigi** [comment]
So I removed the contrast for tables.
