### ISSUE TITLE
Please make wall-paper opt in

### ISSUE THREAD

**Issue by onedayitwillmake** [mallowigi/material-theme-jetbrains-eap#64]
Please make the wall paper opt in.
I tried to disable it, but that option doesn't seem to do anything

**Comment by onedayitwillmake** [comment]
Modifying the source to point to a flat 1 color wallpaper does work though, so that is a decent work around for now

**Comment by mallowigi** [comment]
Unchecking the checkbox is not disabling the wallpaper but rather preventing the plugin from changing it. To disable it, you will have to remove the value in the textfield while leaving the checkbox on.

Maybe I'll need to change the labels.

**Comment by nazrhyn** [comment]
That's interesting; I haven't often seen an option where the checkbox acts as a sort of "lock" on modifying its value. It'd be much more intuitive if that checkbox was whether or not the setting was "active". If it were unchecked, the value would be cleared.

That said, I unchecked it and the value was cleared, but maybe that was an earlier implementation that worked like that?

**Comment by mallowigi** [comment]
Yeah I agree that was my prior implementation but the problem is that there were users who have already set up a background and the plugin was preventing them of using their own, because checking it would use the option settings whereas unchecking it would have resetted it to null.

**Comment by mallowigi** [comment]
Yeah that was my first choice as well but then people who would uncheck the checkbox and use their own wp would get welcomed by having their wallpaper reset after restarting the ide so it was far from perfect

**Comment by nazrhyn** [comment]
I sympathize :face_with_head_bandage:.

**Comment by josephtaylor** [comment]
why not just remove the wallpaper thing altogether? Was that a feature people wanted? It looks really out of place to me.
