### ISSUE TITLE
Preview background color

### ISSUE THREAD

**Issue by onatakduman** [mallowigi/material-theme-jetbrains-eap#66]
![aaaaa](https://user-images.githubusercontent.com/19240652/27585821-6551203a-5b46-11e7-8e49-8f6eee334570.PNG)

How can i change Preview Screen background and other Dracula UI colors?

I like this UI and I wanna use/see same UI colors and things, thank you for made the UI.

**Comment by mallowigi** [comment]
What do you mean, it already uses the same colors.

**Comment by onatakduman** [comment]
I mean background color of Preview Editor

**Comment by mallowigi** [comment]
If it didn't change, that means that it was hardcoded by the Jetbrains team. So you can't.

**Comment by onatakduman** [comment]
Okey
