### ISSUE TITLE
Glitches with Editor Theme in IntelliJ IDEA 2017.1.4

### ISSUE THREAD

**Issue by J-Van** [mallowigi/material-theme-jetbrains-eap#67]
I'm having a problem very similar to https://github.com/mallowigi/material-theme-jetbrains-eap/issues/48, except it's happening in two of my PCs both in Windows 10.

**Plugin version:** Material Theme UI EAP 0.4.4.1. It could from a previous version, as I only recently selected the 'Restore defaults...' option for the Editor Scheme.

Ever since I updated the color scheme to the latest version, I've been having that problem with certain parts of the UI disappearing and not refreshing properly. For example:

![idea64_2017-06-27_12-59-46](https://user-images.githubusercontent.com/10927780/27604621-724fa074-5b3f-11e7-9e10-c4d2a39c8b44.png)

Apart from obfuscating the code, I have not edited the image in any other way. Notice how all the file tabs, tool windows and most of the code is missing. This happened after minimizing and then restoring the IDEA window. Scrolling the code up and down will make it appear again, while hovering over most of the missing buttons will make them reappear too.

I've also noticed that in my case it only happens with Scala files, since I tried to replicate it with Java files in that same project unsuccessfully. I have not tested any other languages, but at least it's been happening consistently in Scala.

Only the editor theme (color scheme) causes this problem, the global IDE theme doesn't cause it at all. Here's another example with this project: https://github.com/playframework/play-scala-starter-example

![idea64_2017-06-27_13-14-07](https://user-images.githubusercontent.com/10927780/27605432-4dc6c22a-5b42-11e7-9eee-5756700e3347.png)

After opening Results.scala (a file from the Play framework) and closing it, the editor should have opened CountController.scala as it is in the next tab. Instead, only lines 23 and 24 updated, the rest of the code is still from Results.scala and Results.scala still appears in the tabs at the top even after being closed. Minimizing and restoring the window at this point results in this:

![idea64_2017-06-27_13-16-19](https://user-images.githubusercontent.com/10927780/27607516-bc81fc96-5b49-11e7-9c5b-4918a235a68d.png)

Only a single word ('Ok') from CountController.scala is still visible and the rest disappeared. Parts of the UI are also obscured with grey blocks, even partially, as seen in the bottom with the bar showing the current theme and git branch, and in the file breadcrumbs at the top.

Testing with even another project, https://github.com/Azure/mmlspark, the exact same problem occurred. Here:

![idea64_2017-06-27_13-32-30](https://user-images.githubusercontent.com/10927780/27609385-323f04c8-5b50-11e7-91cf-618faad30a18.png)

This was the result of minimizing, restoring, and then resizing the window. The right part of the window doesn't refresh properly and shows black boxes all around, while the code completely disappeared from the editor window.

Using an older scheme that I had in backup doesn't have these problems, I'll provide it here:

[_@user_Material Theme - Darker.zip](https://github.com/mallowigi/material-theme-jetbrains-eap/files/1106732/_.user_Material.Theme.-.Darker.zip)

I'll be happy to provide any other info that you could need.

**Comment by mallowigi** [comment]
try with what I said in the end of the thread: 
https://github.com/ChrisRM/material-theme-jetbrains/issues/358

**Comment by J-Van** [comment]
That seemed to have done the trick, at least there are no more glitches that I can see. I'll keep an eye out just in case.

Reading that thread, the problem was fixed in a version of the Scala plugin that is still unreleased?

**Comment by mallowigi** [comment]
it is released for 2017.2 release candidate
