### ISSUE TITLE
Fix issue with background image:

### ISSUE THREAD

**Issue by mallowigi** [mallowigi/material-theme-jetbrains-eap#69]
When IDE is up, check background image:
- save into different property (CUSTOM_BG) if different from default
- listen when image is set from ide and update property
- if plugin is uninstalled restore previous property or null
- if checkbox is unset load from property only but if set load from MT property

**Comment by BloodShura** [comment]
Even if I change the background image, everytime I load the IDE again, the plugin is restoring to it's default (https://raw.githubusercontent.com/mallowigi/material-theme-jetbrains-eap/master/src/main/resources/themes/wall.jpg).

**Comment by mallowigi** [comment]
should be fixed in latest version

**Comment by JamesLefrere** [comment]
I'm still getting this issue in version 1.3.0-171.2953
