### ISSUE TITLE
Visual issues when unchecking Material Design Components

### ISSUE THREAD

**Issue by nazrhyn** [mallowigi/material-theme-jetbrains-eap#75]
With the Material Design Components setting unchecked, there are some definite visual issues with several elements. I feel like I remember you saying that those issues were known and a low priority for you, but I can't remember where you said that. If that's the case, maybe you can use this issue for tracking the work in the future.

## Material
![image](https://user-images.githubusercontent.com/1672405/28083619-f94aa1c8-6643-11e7-9e8f-245a055db72b.png)

![image](https://user-images.githubusercontent.com/1672405/28083628-01820822-6644-11e7-9bb9-caa54e047660.png)

![image](https://user-images.githubusercontent.com/1672405/28083649-0afe2282-6644-11e7-845f-bc5d32f589bb.png)

![image](https://user-images.githubusercontent.com/1672405/28083712-52d7f79a-6644-11e7-9b60-7d6dad436d45.png)   
_Background color doesn't fill numeric up/down. (This is a problem in both states.)_

## Not Material
![image](https://user-images.githubusercontent.com/1672405/28083466-6f650156-6643-11e7-869f-09985b388519.png)   
_Buttons still appear to have the material background while also having the old borders. Active highlight looks strange._

![image](https://user-images.githubusercontent.com/1672405/28083488-815ebeb0-6643-11e7-9ecb-52e64a4f348c.png)   
_Help button bottom left of settings dialog._

![image](https://user-images.githubusercontent.com/1672405/28083504-916a8762-6643-11e7-91ac-94ea8ae18c01.png)   
_Disabled buttons._

![image](https://user-images.githubusercontent.com/1672405/28083521-99ffa9a2-6643-11e7-9419-ffb55c2d5da8.png)   
_Background color doesn't fill numeric up/down._

**Comment by mallowigi** [comment]
Yep, that's because even though you are disabling the components LAF, the IDE still uses the colors from the Material Theme...

I can see some issues though:
- The spinner needs a rewrite anyway
- It's the first time I saw this about the buttons oO definitely gonna take a look

**Comment by mallowigi** [comment]
Things should be better now (though I didnt test thoroughly because it's pretty late)

**Comment by nazrhyn** [comment]
Buttons and help icon look great!

![image](https://user-images.githubusercontent.com/1672405/28141483-b9e26664-672a-11e7-9686-a6e98071fae0.png)

![image](https://user-images.githubusercontent.com/1672405/28141486-be05c3ee-672a-11e7-82d1-bc7e8a575ea4.png)

The numeric up/down is still a little strange looking.

![image](https://user-images.githubusercontent.com/1672405/28141509-d7c8b494-672a-11e7-9dcf-ef43e6b53dff.png)

Definite improvement though!

**Comment by mallowigi** [comment]
Yep as I said, the spinner needs a rewrite so I didn't work on it at all.

--
Elior
