### ISSUE TITLE
automatic highlighting (for variables) and manual highlighting are hard to distinguish

### ISSUE THREAD

**Issue by pakro** [mallowigi/material-theme-jetbrains-eap#79]
I'm often not able to see what I manually highlighted when I'm e. g. trying to copy a variable name or parts of it since it is automatically highlighted and both grey tones are very very hard to distinguish if you have bad light conditions or not cranked up the brightness on your monitor.

Would it be possible to clearly differentiate both colors?

**Comment by mallowigi** [comment]
what language?

**Comment by pakro** [comment]
Java and JavaScript (TypeScript). Not sure about other languages.

**Comment by mallowigi** [comment]
I understand, but unfortunately I don't have any answer for that. This comes from the original color scheme.
