### ISSUE TITLE
uh...How can I disable this mouse hint... 

### ISSUE THREAD

**Issue by xinkunZ** [mallowigi/material-theme-jetbrains-eap#83]
![image](https://user-images.githubusercontent.com/7759897/28558705-a6bc7d20-7145-11e7-83bb-3a0a66a5009b.png)
It not works well , and a little tilted..

**Comment by mallowigi** [comment]
I will work out something for the next version

**Comment by xinkunZ** [comment]
HaHa.. Do you have any job? I almost think you work for this plugin all day...

**Comment by mallowigi** [comment]
Don't tell my boss ;)

**Comment by mallowigi** [comment]
should be better now :)
