### ISSUE TITLE
Darker Theme - Stack trace nearly unreadable

### ISSUE THREAD

**Issue by nazrhyn** [mallowigi/material-theme-jetbrains-eap#98]
### Summary
In the Darker theme, stack frames from "library" files are nearly unreadable.

### Expected behavior
![image](https://user-images.githubusercontent.com/1672405/28588754-96b9c6c2-7149-11e7-8913-1d58c2671be2.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/1672405/28588682-532b9854-7149-11e7-9230-c749cc0efa3f.png)

### Environment
```
WebStorm 2017.2
Build #WS-172.3317.70, built on July 14, 2017
Licensed to Christopher Harwood
You have a perpetual fallback license for this version
Subscription is active until September 18, 2018
JRE: 1.8.0_152-release-915-b5 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1
```

**Comment by mallowigi** [comment]
where is this library?

**Comment by nazrhyn** [comment]
That's just the behavior in WebStorm. Stack frames from "Library" files are colored differently. For example: stuff in `node_modules/` or Node.js code.

**Comment by mallowigi** [comment]
Forgot to add this to other themes -_-
